/* SSE implementation of Frameshift Aware Forward and Backward algorithms.
 *
 * Both profile and DP matrix are striped and interleaved, for fast
 * SIMD vector operations. Calculations are in probability space
 * (scaled odds ratios, actually) rather than log probabilities,
 * allowing fast multiply/add operations rather than slow Logsum()
 * calculations. Sparse rescaling is used to achieve full dynamic
 * range of scores.
 *
 * The Forward and Backward implementations may be used either in a
 * full O(ML) mode that keeps an entire DP matrix, or in a O(M+L)
 * linear memory "parsing" mode that only keeps one row of memory for
 * the main MDI states and one column 0..L for the special states
 * B,E,N,C,J. Keeping a full matrix allows subsequent stochastic
 * traceback or posterior decoding of any state. In parsing mode, we
 * can do posterior decoding on the special states and determine
 * regions of the target sequence that are generated by the
 * nonhomology states (NCJ) versus not -- thus, identifying where
 * high-probability "regions" are, the first step of identifying the
 * domain structure of a target sequence.
 *
 * Contents:
 *   1. Forward/Backward 
 *   2. Benchmark driver.
 *   3. Unit tests.
 *   4. Test driver.
 *   5. Example.
 *
 * SRE, Thu Jul 31 08:43:20 2008 [Janelia]
 */
#include "p7_config.h"

#include <stdio.h>
#include <math.h>

#include <xmmintrin.h>		/* SSE  */
#include <emmintrin.h>		/* SSE2 */

#include "easel.h"
#include "esl_alphabet.h"
#include "esl_gencode.h"
#include "esl_sse.h"

#include "hmmer.h"
#include "impl_sse.h"

/* IVX intermediate matrix access: [slot 0..p7P_3CODONS-1][stripe 0..Q-1] */
#define IVX(slot, q) (ivxf[(slot)*Q + (q)])

/*****************************************************************
 * 1. Forward/Backward
 *****************************************************************/

/* Function:  p7_ForwardParser_Frameshift_3Codons_SSE()
 * Synopsis:  SSE-accelerated frameshift-aware Forward algorithm, 3 codon lengths, linear memory.
 *
 * Purpose:   The Forward dynamic programming algorithm for frameshift-aware
 *            translated comparison between a nucleotide sequence and a
 *            frameshift-aware codon HMM, using three codon lengths (2, 3, 4
 *            nucleotides), implemented with SIMD parallelism and sparse
 *            rescaling for full floating-point dynamic range.
 *
 *            Given a digital nucleotide sequence <dsq> of length <L>, an
 *            optimized frameshift profile <om_fs> (codon_lengths == 3), and a
 *            DP matrix <ox> allocated for at least PARSER_ROWS_FWD MDI rows
 *            and L special-state rows, computes the Forward probability of the
 *            sequence given the model and returns the Forward score in nats in
 *            <*opt_sc>.
 *
 *            Calculations are in probability space (odds ratios) with sparse
 *            rescaling. The profile must be in local alignment mode.
 *
 *            The intermediate value matrix (IVX) is allocated locally as
 *            p7P_3CODONS circular rows of Q SIMD vectors each. MDI rows in
 *            <ox> are used in a circular fashion (PARSER_ROWS_FWD = 4 rows).
 *            Special states are maintained in scalar circular buffers of size
 *            PARSER_ROWS_FWD; only the scale factors and final special state
 *            values are written to ox->xmx.
 *
 *            The caller must allocate <ox> with at least PARSER_ROWS_FWD
 *            valid MDI rows (ox->validR >= PARSER_ROWS_FWD) and L+1 X-rows
 *            (ox->allocXR > L).
 *
 * Args:      dsq    - nucleotide sequence in digitized form, 1..L
 *            gcode  - genetic code table (for nucleotide alphabet)
 *            L      - length of dsq
 *            om_fs  - optimized frameshift profile (codon_lengths must be 3)
 *            ox     - DP matrix with PARSER_ROWS_FWD MDI rows and L X rows
 *            opt_sc - optRETURN: Forward score in nats
 *
 * Returns:   <eslOK> on success.
 *
 * Throws:    <eslEINVAL> if profile or matrix allocation is incorrect.
 *            <eslERANGE> if score overflows or underflows.
 *            In either case, <*opt_sc> is undefined.
 */
int
p7_ForwardParser_Frameshift_3Codons_SSE(const ESL_DSQ *dsq, const ESL_GENCODE *gcode, int L,
                                         const P7_FS_OPROFILE *om_fs, P7_OMX *ox, float *opt_sc)
{
  register __m128 mpv2, dpv2, ipv2;   /* right-shifted prev2 row MDI for BM/MM/IM/DM   */
  register __m128 sv;                 /* temporary IVX accumulator                      */
  register __m128 msv;                /* M state accumulator for current position       */
  register __m128 dcv;                /* delayed D(i,q+1) = M(i,q)*tMD carry value     */
  register __m128 xEv;                /* E state sum: horizontal reduce to scalar xE    */
  register __m128 xBv2;               /* splatted B(i-2) for B->Mk transitions          */
  __m128   zerov;                     /* splatted 0.0                                   */
  float    xN, xE, xB, xC, xJ;        /* special state values at position i             */
  float    xN_buf[PARSER_ROWS_FWD];   /* circular buffer: N(i) at slot i%PARSER_ROWS_FWD */
  float    xB_buf[PARSER_ROWS_FWD];   /* circular buffer: B(i) at slot i%PARSER_ROWS_FWD */
  float    xJ_buf[PARSER_ROWS_FWD];   /* circular buffer: J(i) at slot i%PARSER_ROWS_FWD */
  float    xC_buf[PARSER_ROWS_FWD];   /* circular buffer: C(i) at slot i%PARSER_ROWS_FWD */
  int      b, b2, b3;                 /* buffer slots for i, i-2, i-3                  */
  int      curr, prev2, prev3;        /* MDI row indices (circular mod PARSER_ROWS_FWD) */
  int      ivx_2, ivx_3, ivx_4;       /* IVX slot indices for rows at i, i-1, i-2      */
  __m128  *dpc, *dpp2, *dpp3;         /* MDI DP row pointers                            */
  __m128  *tp;                        /* steps through om_fs->tfv transitions           */
  __m128  *ivxf     = NULL;           /* IVX intermediate matrix [slot*Q + q]           */
  __m128  *ivxf_mem = NULL;           /* unaligned alloc backing ivxf                   */
  int      Q = p7O_NQF(om_fs->M);     /* number of SIMD float stripes                   */
  int      i, q, j, r;
  int      c2, c3, c4;                /* codon emission table indices                   */
  int      u, v, w, x;                /* rolling nucleotide window for codon lookup      */
  int      status;

  /* Validate inputs */
  if (om_fs->codon_lengths != 3) ESL_EXCEPTION(eslEINVAL, "profile not allocated for 3 codon lengths");

#if eslDEBUGLEVEL > 0
  if (om_fs->M > ox->allocQ4*4)        ESL_EXCEPTION(eslEINVAL, "DP matrix allocated too small (too few columns)");
  if (ox->validR < PARSER_ROWS_FWD)    ESL_EXCEPTION(eslEINVAL, "DP matrix needs at least PARSER_ROWS_FWD MDI rows");
  if (L >= ox->allocXR)                ESL_EXCEPTION(eslEINVAL, "DP matrix allocated too small (too few X rows)");
  if (! p7_fs_oprofile_IsLocal(om_fs)) ESL_EXCEPTION(eslEINVAL, "Forward implementation assumes local alignment mode");
#endif

  ox->M  = om_fs->M;
  ox->L  = L;
  ox->has_own_scales = TRUE;
  ox->totscale       = 0.0;
  zerov = _mm_setzero_ps();

  /* Allocate and align IVX: p7P_3CODONS circular rows x Q stripes */
  ESL_ALLOC(ivxf_mem, sizeof(__m128) * p7P_3CODONS * Q + 15);
  ivxf = (__m128 *) (((unsigned long int) ivxf_mem + 15) & (~0xf));

  /* Zero-initialize all PARSER_ROWS_FWD MDI rows */
  for (r = 0; r < PARSER_ROWS_FWD; r++)
    for (q = 0; q < Q; q++)
      MMO(ox->dpf[r],q) = IMO(ox->dpf[r],q) = DMO(ox->dpf[r],q) = zerov;

  /* Zero-initialize all p7P_3CODONS IVX rows */
  for (r = 0; r < p7P_3CODONS; r++)
    for (q = 0; q < Q; q++)
      IVX(r, q) = zerov;

  /* Initialize circular special-state buffers.
   * Slots 0 and 1 correspond to positions i=0 and i=1.
   * N(0)=N(1)=1.0 (no N->N recursion before first complete codon).
   * B(0)=B(1)=T_NM. E=J=C=0 for all slots initially.
   */
  for (r = 0; r < PARSER_ROWS_FWD; r++)
    xN_buf[r] = xB_buf[r] = xJ_buf[r] = xC_buf[r] = 0.0f;
  xN_buf[0] = xN_buf[1] = 1.0f;
  xB_buf[0] = xB_buf[1] = om_fs->xf[p7O_N][p7O_MOVE];

  /* Write i=0 and i=1 specials to ox->xmx */
  ox->xmx[p7X_SCALE] = 1.0;
  ox->xmx[p7X_E]     = 0.0;
  ox->xmx[p7X_N]     = 1.0;
  ox->xmx[p7X_J]     = 0.0;
  ox->xmx[p7X_B]     = om_fs->xf[p7O_N][p7O_MOVE];
  ox->xmx[p7X_C]     = 0.0;
  ox->xmx[1*p7X_NXCELLS+p7X_SCALE] = 1.0;
  ox->xmx[1*p7X_NXCELLS+p7X_E]     = 0.0;
  ox->xmx[1*p7X_NXCELLS+p7X_N]     = 1.0;
  ox->xmx[1*p7X_NXCELLS+p7X_J]     = 0.0;
  ox->xmx[1*p7X_NXCELLS+p7X_B]     = om_fs->xf[p7O_N][p7O_MOVE];
  ox->xmx[1*p7X_NXCELLS+p7X_C]     = 0.0;

  /* Initialize nucleotide rolling window.
   * u=v=placeholder (positions before sequence start).
   * w=dsq[1], x=dsq[2] for the i=2 initialization.
   */
  u = v = p7P_MAXCODONS3;
  if (esl_abc_XIsCanonical(gcode->nt_abc, dsq[1])) w = dsq[1]; else w = p7P_MAXCODONS3;
  if (esl_abc_XIsCanonical(gcode->nt_abc, dsq[2])) x = dsq[2]; else x = p7P_MAXCODONS3;

  /*----------------------------------------------------------------
   * Initialization: i=2
   * Only length-2 quasi-codon (c2 = dsq[1..2]) contributes.
   * IVX(ivx_2) comes from B(0)*BM only (prev2=row0 MDI are all 0).
   * IVX(ivx_3), IVX(ivx_4) are all zero (just initialized).
   * I(2,k) = 0 (prev3=row3 MDI are all zero).
   *----------------------------------------------------------------*/
  i = 2;
  c2 = p7P_CODON2_FS3(w, x); c2 = p7P_MINIDX(c2, p7P_DEGEN3_QC1);

  curr  = 2;  /* i % PARSER_ROWS_FWD */
  prev2 = 0;  /* (i-2) % PARSER_ROWS_FWD */
  prev3 = 3;  /* (i-3+PARSER_ROWS_FWD) % PARSER_ROWS_FWD; all zeros */
  ivx_2 = 2;  /* i % p7P_3CODONS */
  ivx_3 = 1;  /* (i-1) % p7P_3CODONS; all zeros */
  ivx_4 = 0;  /* (i-2) % p7P_3CODONS; all zeros */

  dpc  = ox->dpf[curr];
  dpp2 = ox->dpf[prev2];   /* all zeros */
  dpp3 = ox->dpf[prev3];   /* all zeros */

  xBv2 = _mm_set1_ps(xB_buf[0]);   /* B(0) */
  tp   = om_fs->tfv;
  dcv  = zerov;
  xEv  = zerov;
  /* Right-shifts of all-zero row 0 are all zero */
  mpv2 = dpv2 = ipv2 = zerov;

  for (q = 0; q < Q; q++)
    {
      /* IVX(ivx_2,q) = B(0)*BM[k-1] only; MM/IM/DM are zero */
      sv  =                _mm_mul_ps(xBv2, *tp); tp++;   /* BM */
      sv  = _mm_add_ps(sv, _mm_mul_ps(mpv2, *tp)); tp++;  /* MM (= 0) */
      sv  = _mm_add_ps(sv, _mm_mul_ps(ipv2, *tp)); tp++;  /* IM (= 0) */
      sv  = _mm_add_ps(sv, _mm_mul_ps(dpv2, *tp)); tp++;  /* DM (= 0) */
      IVX(ivx_2, q) = sv;

      /* M(2,q) = IVX(ivx_2,q) * R2(q); IVX(ivx_3,ivx_4) are zero */
      msv = _mm_mul_ps(sv, om_fs->rfv[c2][q]);
      xEv = _mm_add_ps(xEv, msv);

      MMO(dpc, q) = msv;
      DMO(dpc, q) = dcv;

      dcv = _mm_mul_ps(msv, *tp); tp++;   /* MD: carry M(i,q)*tMD into D(i,q+1) */

      /* I(2,q) = 0 (dpp3 is all zeros) */
      IMO(dpc, q) = zerov;
      tp += 2;  /* skip MI, II */
    }

  /* DD paths for row 2 */
  dcv        = esl_sse_rightshiftz_float(dcv);
  DMO(dpc,0) = zerov;
  tp         = om_fs->tfv + 7*Q;
  for (q = 0; q < Q; q++)
    {
      DMO(dpc, q) = _mm_add_ps(dcv, DMO(dpc, q));
      dcv         = _mm_mul_ps(DMO(dpc, q), *tp); tp++;
    }
  if (om_fs->M < 100)
    {
      for (j = 1; j < 4; j++)
        {
          dcv = esl_sse_rightshiftz_float(dcv);
          tp  = om_fs->tfv + 7*Q;
          for (q = 0; q < Q; q++)
            {
              DMO(dpc, q) = _mm_add_ps(dcv, DMO(dpc, q));
              dcv         = _mm_mul_ps(dcv, *tp); tp++;
            }
        }
    }
  else
    {
      for (j = 1; j < 4; j++)
        {
          register __m128 cv;
          dcv = esl_sse_rightshiftz_float(dcv);
          tp  = om_fs->tfv + 7*Q;
          cv  = zerov;
          for (q = 0; q < Q; q++)
            {
              sv          = _mm_add_ps(dcv, DMO(dpc, q));
              cv          = _mm_or_ps(cv, _mm_cmpgt_ps(sv, DMO(dpc, q)));
              DMO(dpc, q) = sv;
              dcv         = _mm_mul_ps(dcv, *tp); tp++;
            }
          if (! _mm_movemask_ps(cv)) break;
        }
    }

  /* Add D contributions and horizontal-sum xEv → xE */
  for (q = 0; q < Q; q++) xEv = _mm_add_ps(DMO(dpc, q), xEv);
  xEv = _mm_add_ps(xEv, _mm_shuffle_ps(xEv, xEv, _MM_SHUFFLE(0, 3, 2, 1)));
  xEv = _mm_add_ps(xEv, _mm_shuffle_ps(xEv, xEv, _MM_SHUFFLE(1, 0, 3, 2)));
  _mm_store_ss(&xE, xEv);

  /* Special states at i=2: N is held constant at 1.0 (no N->N recursion yet) */
  xN = 1.0f;
  xJ = xE * om_fs->xf[p7O_E][p7O_LOOP];
  xC = xE * om_fs->xf[p7O_E][p7O_MOVE];
  xB = xN * om_fs->xf[p7O_N][p7O_MOVE] + xJ * om_fs->xf[p7O_J][p7O_MOVE];

  /* Sparse rescaling at i=2 */
  if (xE > 1.0e4f)
    {
      float scale_factor = 1.0f / xE;
      xN *= scale_factor; xJ *= scale_factor; xC *= scale_factor; xB *= scale_factor;
      xEv = _mm_set1_ps(scale_factor);
      for (r = 0; r < PARSER_ROWS_FWD; r++)
        for (q = 0; q < Q; q++)
          {
            MMO(ox->dpf[r], q) = _mm_mul_ps(MMO(ox->dpf[r], q), xEv);
            DMO(ox->dpf[r], q) = _mm_mul_ps(DMO(ox->dpf[r], q), xEv);
            IMO(ox->dpf[r], q) = _mm_mul_ps(IMO(ox->dpf[r], q), xEv);
          }
      for (r = 0; r < p7P_3CODONS; r++)
        for (q = 0; q < Q; q++)
          IVX(r, q) = _mm_mul_ps(IVX(r, q), xEv);
      for (r = 0; r < PARSER_ROWS_FWD; r++)
        {
          xN_buf[r] *= scale_factor; xB_buf[r] *= scale_factor;
          xJ_buf[r] *= scale_factor; xC_buf[r] *= scale_factor;
        }
      ox->xmx[2*p7X_NXCELLS+p7X_SCALE] = xE;
      ox->totscale += log(xE);
      xE = 1.0f;
    }
  else ox->xmx[2*p7X_NXCELLS+p7X_SCALE] = 1.0f;

  /* Store i=2 specials to circular buffers and ox->xmx */
  xN_buf[2] = xN; xB_buf[2] = xB; xJ_buf[2] = xJ; xC_buf[2] = xC;
  ox->xmx[2*p7X_NXCELLS+p7X_E] = xE;
  ox->xmx[2*p7X_NXCELLS+p7X_N] = xN;
  ox->xmx[2*p7X_NXCELLS+p7X_J] = xJ;
  ox->xmx[2*p7X_NXCELLS+p7X_B] = xB;
  ox->xmx[2*p7X_NXCELLS+p7X_C] = xC;

  /*----------------------------------------------------------------
   * Main recurrence: i = 3..L
   *
   * M(i,k) = [ B(i-2)*BM(k-1) + M(i-2,k-1)*MM(k-1)
   *            + I(i-2,k-1)*IM(k-1) + D(i-2,k-1)*DM(k-1) ] * R2(k)   [2-nt codon]
   *          + IVX(i-1,k) * R3(k)                                       [3-nt codon]
   *          + IVX(i-2,k) * R4(k)                                       [4-nt codon]
   *
   * where IVX(i,k) holds the pre-emission entry value from row i
   * (computed at iteration i+1 as the i-2 contribution for that row).
   *
   * I(i,k) = M(i-3,k)*MI(k) + I(i-3,k)*II(k)    (same stripe, no right-shift)
   * D(i,k) = M(i,k-1)*MD(k-1) + D(i,k-1)*DD(k-1) (within-row serialization)
   *
   * N(i) = N(i-3)*T_NL
   * J(i) = J(i-3)*T_JL + E(i)*T_EL
   * C(i) = C(i-3)*T_CL + E(i)*T_EM
   * B(i) = N(i)*T_NM + J(i)*T_JM
   *
   * Special states reference i-3 buffers; IVX and M->D use i-2 (prev2).
   *----------------------------------------------------------------*/
  for (i = 3; i <= L; i++)
    {
      /* Advance nucleotide window */
      u = v; v = w; w = x;
      if (esl_abc_XIsCanonical(gcode->nt_abc, dsq[i])) x = dsq[i]; else x = p7P_MAXCODONS3;

      /* Look up codon emission table indices */
      c2 = p7P_CODON2_FS3(w, x); c2 = p7P_MINIDX(c2, p7P_DEGEN3_QC1);
      c3 = p7P_CODON3_FS3(v, w, x); c3 = p7P_MINIDX(c3, p7P_DEGEN3_C);
      c4 = p7P_CODON4_FS3(u, v, w, x); c4 = p7P_MINIDX(c4, p7P_DEGEN3_QC1);

      /* Circular MDI row indices */
      curr  =     i               % PARSER_ROWS_FWD;
      prev2 = ((i-2) % PARSER_ROWS_FWD + PARSER_ROWS_FWD) % PARSER_ROWS_FWD;
      prev3 = ((i-3) % PARSER_ROWS_FWD + PARSER_ROWS_FWD) % PARSER_ROWS_FWD;

      /* IVX slot indices */
      ivx_2 =     i               % p7P_3CODONS;
      ivx_3 = ((i-1) % p7P_3CODONS + p7P_3CODONS) % p7P_3CODONS;
      ivx_4 = ((i-2) % p7P_3CODONS + p7P_3CODONS) % p7P_3CODONS;

      /* Circular special-state buffer indices */
      b  =     i               % PARSER_ROWS_FWD;
      b2 = ((i-2) % PARSER_ROWS_FWD + PARSER_ROWS_FWD) % PARSER_ROWS_FWD;
      b3 = ((i-3) % PARSER_ROWS_FWD + PARSER_ROWS_FWD) % PARSER_ROWS_FWD;

      dpc  = ox->dpf[curr];
      dpp2 = ox->dpf[prev2];
      dpp3 = ox->dpf[prev3];

      /* Right-shift prev2 MDI for (k-1) indexing in BM/MM/IM/DM transitions */
      mpv2 = esl_sse_rightshiftz_float(MMO(dpp2, Q-1));
      dpv2 = esl_sse_rightshiftz_float(DMO(dpp2, Q-1));
      ipv2 = esl_sse_rightshiftz_float(IMO(dpp2, Q-1));

      xBv2 = _mm_set1_ps(xB_buf[b2]);   /* B(i-2) splatted */
      tp   = om_fs->tfv;
      dcv  = zerov;
      xEv  = zerov;

      for (q = 0; q < Q; q++)
        {
          /* IVX(ivx_2,q): pre-emission entry from row i-2 into match position k */
          sv  =                _mm_mul_ps(xBv2, *tp); tp++;   /* BM: B(i-2) -> Mk  */
          sv  = _mm_add_ps(sv, _mm_mul_ps(mpv2, *tp)); tp++;  /* MM: M(i-2,k-1)    */
          sv  = _mm_add_ps(sv, _mm_mul_ps(ipv2, *tp)); tp++;  /* IM: I(i-2,k-1)    */
          sv  = _mm_add_ps(sv, _mm_mul_ps(dpv2, *tp)); tp++;  /* DM: D(i-2,k-1)    */
          IVX(ivx_2, q) = sv;

          /* M(i,k) = IVX(ivx_2)*R2 + IVX(ivx_3)*R3 + IVX(ivx_4)*R4 */
          msv =                _mm_mul_ps(sv,              om_fs->rfv[c2][q]);
          msv = _mm_add_ps(msv, _mm_mul_ps(IVX(ivx_3, q), om_fs->rfv[c3][q]));
          msv = _mm_add_ps(msv, _mm_mul_ps(IVX(ivx_4, q), om_fs->rfv[c4][q]));
          xEv = _mm_add_ps(xEv, msv);

          /* Update prev2 (k-1) values for next stripe q */
          mpv2 = MMO(dpp2, q);
          dpv2 = DMO(dpp2, q);
          ipv2 = IMO(dpp2, q);

          /* Store M(i,q); store delayed D(i,q) from previous q's carry */
          MMO(dpc, q) = msv;
          DMO(dpc, q) = dcv;

          /* Carry M(i,q)*tMD into D(i,q+1) */
          dcv = _mm_mul_ps(msv, *tp); tp++;   /* MD */

          /* I(i,k) = M(i-3,k)*MI + I(i-3,k)*II  (same stripe, no right-shift) */
          sv          =                _mm_mul_ps(MMO(dpp3, q), *tp); tp++;  /* MI */
          IMO(dpc, q) = _mm_add_ps(sv, _mm_mul_ps(IMO(dpp3, q), *tp)); tp++;  /* II */
        }

      /* DD paths: serialize D(i,k) = M(i,k-1)*MD + D(i,k-1)*DD
       * (same 4-pass serialization as forward_engine)
       */
      dcv        = esl_sse_rightshiftz_float(dcv);
      DMO(dpc,0) = zerov;
      tp         = om_fs->tfv + 7*Q;
      for (q = 0; q < Q; q++)
        {
          DMO(dpc, q) = _mm_add_ps(dcv, DMO(dpc, q));
          dcv         = _mm_mul_ps(DMO(dpc, q), *tp); tp++;
        }
      if (om_fs->M < 100)
        {
          for (j = 1; j < 4; j++)
            {
              dcv = esl_sse_rightshiftz_float(dcv);
              tp  = om_fs->tfv + 7*Q;
              for (q = 0; q < Q; q++)
                {
                  DMO(dpc, q) = _mm_add_ps(dcv, DMO(dpc, q));
                  dcv         = _mm_mul_ps(dcv, *tp); tp++;
                }
            }
        }
      else
        {
          for (j = 1; j < 4; j++)
            {
              register __m128 cv;
              dcv = esl_sse_rightshiftz_float(dcv);
              tp  = om_fs->tfv + 7*Q;
              cv  = zerov;
              for (q = 0; q < Q; q++)
                {
                  sv          = _mm_add_ps(dcv, DMO(dpc, q));
                  cv          = _mm_or_ps(cv, _mm_cmpgt_ps(sv, DMO(dpc, q)));
                  DMO(dpc, q) = sv;
                  dcv         = _mm_mul_ps(dcv, *tp); tp++;
                }
              if (! _mm_movemask_ps(cv)) break;
            }
        }

      /* Add D contributions to xEv, horizontal-sum → scalar xE */
      for (q = 0; q < Q; q++) xEv = _mm_add_ps(DMO(dpc, q), xEv);
      xEv = _mm_add_ps(xEv, _mm_shuffle_ps(xEv, xEv, _MM_SHUFFLE(0, 3, 2, 1)));
      xEv = _mm_add_ps(xEv, _mm_shuffle_ps(xEv, xEv, _MM_SHUFFLE(1, 0, 3, 2)));
      _mm_store_ss(&xE, xEv);

      /* Special state recursions using i-3 circular buffer values */
      xN = xN_buf[b3] * om_fs->xf[p7O_N][p7O_LOOP];
      xJ = xJ_buf[b3] * om_fs->xf[p7O_J][p7O_LOOP] + xE * om_fs->xf[p7O_E][p7O_LOOP];
      xC = xC_buf[b3] * om_fs->xf[p7O_C][p7O_LOOP] + xE * om_fs->xf[p7O_E][p7O_MOVE];
      xB = xN         * om_fs->xf[p7O_N][p7O_MOVE]  + xJ * om_fs->xf[p7O_J][p7O_MOVE];

      /* Sparse rescaling: when xE exceeds threshold, rescale ALL rows and buffers
       * so that all values remain on the same relative scale.
       * We must rescale all PARSER_ROWS_FWD MDI rows, all p7P_3CODONS IVX rows,
       * and all PARSER_ROWS_FWD entries of every circular special-state buffer.
       */
      if (xE > 1.0e4f)
        {
          float scale_factor = 1.0f / xE;
          xN *= scale_factor; xJ *= scale_factor; xC *= scale_factor; xB *= scale_factor;
          xEv = _mm_set1_ps(scale_factor);
          for (r = 0; r < PARSER_ROWS_FWD; r++)
            for (q = 0; q < Q; q++)
              {
                MMO(ox->dpf[r], q) = _mm_mul_ps(MMO(ox->dpf[r], q), xEv);
                DMO(ox->dpf[r], q) = _mm_mul_ps(DMO(ox->dpf[r], q), xEv);
                IMO(ox->dpf[r], q) = _mm_mul_ps(IMO(ox->dpf[r], q), xEv);
              }
          for (r = 0; r < p7P_3CODONS; r++)
            for (q = 0; q < Q; q++)
              IVX(r, q) = _mm_mul_ps(IVX(r, q), xEv);
          for (r = 0; r < PARSER_ROWS_FWD; r++)
            {
              xN_buf[r] *= scale_factor; xB_buf[r] *= scale_factor;
              xJ_buf[r] *= scale_factor; xC_buf[r] *= scale_factor;
            }
          ox->xmx[i*p7X_NXCELLS+p7X_SCALE] = xE;
          ox->totscale += log(xE);
          xE = 1.0f;
        }
      else ox->xmx[i*p7X_NXCELLS+p7X_SCALE] = 1.0f;

      /* Store specials to circular buffers and ox->xmx */
      xN_buf[b] = xN; xB_buf[b] = xB; xJ_buf[b] = xJ; xC_buf[b] = xC;
      ox->xmx[i*p7X_NXCELLS+p7X_E] = xE;
      ox->xmx[i*p7X_NXCELLS+p7X_N] = xN;
      ox->xmx[i*p7X_NXCELLS+p7X_J] = xJ;
      ox->xmx[i*p7X_NXCELLS+p7X_B] = xB;
      ox->xmx[i*p7X_NXCELLS+p7X_C] = xC;
    } /* end main loop i=3..L */

  /* Final score: C->T transition.
   * Sequence ends after L nucleotides, which may complete a 2-, 3-, or 4-nt
   * codon at positions L, L-1, or L-2 respectively (relative to the last
   * codon start). Sum C-state contributions from those three end positions.
   * All xC_buf values are on the same scale (guaranteed by global rescaling).
   */
  {
    float xCL   = xC_buf[   L    % PARSER_ROWS_FWD];
    float xCLm1 = xC_buf[((L-1) % PARSER_ROWS_FWD + PARSER_ROWS_FWD) % PARSER_ROWS_FWD];
    float xCLm2 = xC_buf[((L-2) % PARSER_ROWS_FWD + PARSER_ROWS_FWD) % PARSER_ROWS_FWD];
    float xCtot = xCL
                + xCLm1 * om_fs->xf[p7O_C][p7O_LOOP]
                + xCLm2 * om_fs->xf[p7O_C][p7O_LOOP];

    if      (isnan(xCtot))           ESL_EXCEPTION(eslERANGE, "forward score is NaN");
    else if (L > 2 && xCtot == 0.0f) ESL_EXCEPTION(eslERANGE, "forward score underflow (is 0.0)");
    else if (isinf(xCtot) == 1)      ESL_EXCEPTION(eslERANGE, "forward score overflow (is infinity)");

    if (opt_sc != NULL)
      *opt_sc = ox->totscale + logf(xCtot * om_fs->xf[p7O_C][p7O_MOVE]);
  }

  free(ivxf_mem);
  return eslOK;

 ERROR:
  if (ivxf_mem) free(ivxf_mem);
  return status;
}

/*-------------- end, forward/backward  -----------------*/




/*****************************************************************
 * 2. Benchmark driver.
 *****************************************************************/


/*------------------- end, benchmark driver ---------------------*/


/*****************************************************************
 * 3. Unit tests.
 *****************************************************************/
#ifdef p7FWDBACKFS_TESTDRIVE
#include "esl_random.h"
#include "esl_randomseq.h"

/*
 * compare to GForward() scores.
 */
static void
utest_fwdbackfs(ESL_RANDOMNESS *r, ESL_ALPHABET *abcAA, ESL_ALPHABET *abcDNA, ESL_GENCODE *gcode, P7_BG *bgAA, P7_BG *bgDNA, int M, int L, int N)
{
  char           *msg    = "forward/backward fs unit test failed";
  P7_HMM         *hmm    = NULL;
  P7_FS_PROFILE  *gm_fs3 = p7_profile_fs_Create(M, abcAA, 3);
  P7_FS_OPROFILE *om_fs3 = p7_fs_oprofile_Create(M, abcAA, 3); 
  ESL_DSQ        *dsq    = malloc(sizeof(ESL_DSQ) * (L+2));
  P7_OMX         *fwd    = p7_omx_Create(M, PARSER_ROWS_FWD, L);
  P7_GMX         *gx     = p7_gmx_fs_Create(M, PARSER_ROWS_FWD, L, 0);
  P7_IVX         *iv     = p7_ivx_Create(M, p7P_3CODONS); 
  float tolerance;
  float fsc3;
  float generic_fsc3;

  p7_FLogsumInit();
  if (p7_FLogsumError(-0.4, -0.5) > 0.0001) tolerance = 1.0;  /* weaker test against GForward()   */
  else tolerance = 0.0001;   /* stronger test: FLogsum() is in slow exact mode. */

  p7_hmm_Sample(r, M, abcAA, &hmm);
  p7_ProfileConfig_fs(hmm, bgAA, gcode, gm_fs3, L/3, p7_LOCAL);
  p7_fs_oprofile_Convert(gm_fs3, om_fs3);
  p7_fs_oprofile_ReconfigLength(om_fs3, L/3);

  while (N--)
    {
      esl_rsq_xfIID(r, bgDNA->f, abcDNA->K, L, dsq);

      p7_ForwardParser_Frameshift_3Codons_SSE(dsq, gcode, L, om_fs3, fwd, &fsc3);	  
	  p7_ForwardParser_Frameshift_3Codons(dsq, gcode, L, gm_fs3, gx, iv, &generic_fsc3);

      /* non simd Forward scores should approximate simd Forward scores,
       * with tolerance that depends on how logsum.c was compiled
       */
      if (fabs(fsc3-generic_fsc3) > tolerance) esl_fatal(msg);
    }

  free(dsq);
  p7_hmm_Destroy(hmm);
  p7_omx_Destroy(fwd);
  p7_gmx_Destroy(gx);
  p7_ivx_Destroy(iv);
  p7_profile_fs_Destroy(gm_fs3);
  p7_fs_oprofile_Destroy(om_fs3);
}
#endif /*p7FWDBACKFS_TESTDRIVE*/
/*---------------------- end, unit tests ------------------------*/



/*****************************************************************
 * 4. Test driver
 *****************************************************************/
#ifdef p7FWDBACKFS_TESTDRIVE
/*
   gcc -g -Wall -msse2 -std=gnu99 -o fwdback_fs_utest -I.. -L.. -I../../easel -L../../easel -Dp7FWDBACKFS_TESTDRIVE fwdback_fs.c -lhmmer -leasel -lm
   ./fwdback_fs_utest
 */
#include "p7_config.h"

#include "easel.h"
#include "esl_alphabet.h"
#include "esl_getopts.h"
#include "esl_random.h"

#include "hmmer.h"
#include "impl_sse.h"

static ESL_OPTIONS options[] = {
  /* name           type      default  env  range toggles reqs incomp  help                                       docgroup*/
  { "-h",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, NULL, "show brief help on version and usage",           0 },
  { "-s",        eslARG_INT,     "42", NULL, NULL,  NULL,  NULL, NULL, "set random number seed to <n>",                  0 },
  { "-L",        eslARG_INT,    "600", NULL, NULL,  NULL,  NULL, NULL, "size of random sequences to sample",             0 },
  { "-M",        eslARG_INT,    "145", NULL, NULL,  NULL,  NULL, NULL, "size of random models to sample",                0 },
  { "-N",        eslARG_INT,    "100", NULL, NULL,  NULL,  NULL, NULL, "number of random sequences to sample",           0 },
  {  0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
};
static char usage[]  = "[-options]";
static char banner[] = "test driver for SSE Forward, Backward implementations";

int
main(int argc, char **argv)
{
  ESL_GETOPTS    *go     = p7_CreateDefaultApp(options, 0, argc, argv, banner, usage);
  ESL_RANDOMNESS *r      = esl_randomness_CreateFast(esl_opt_GetInteger(go, "-s"));
  ESL_GENCODE    *gcode  = NULL;
  ESL_ALPHABET   *abcAA  = NULL;
  ESL_ALPHABET   *abcDNA = NULL;
  P7_BG          *bgAA   = NULL;
  P7_BG          *bgDNA  = NULL;
  int             M      = esl_opt_GetInteger(go, "-M");
  int             L      = esl_opt_GetInteger(go, "-L");
  int             N      = esl_opt_GetInteger(go, "-N");

  if ((abcDNA = esl_alphabet_Create(eslDNA)) == NULL)  esl_fatal("failed to create alphabet");
  if ((bgDNA = p7_bg_Create(abcDNA))         == NULL)  esl_fatal("failed to create null model");
  if ((abcAA = esl_alphabet_Create(eslAMINO)) == NULL)  esl_fatal("failed to create alphabet");
  if ((bgAA = p7_bg_Create(abcAA))            == NULL)  esl_fatal("failed to create null model");
  if ((gcode  = esl_gencode_Create(abcDNA,abcAA)) == NULL)  esl_fatal("failed to create gencode");
   
  utest_fwdbackfs(r, abcAA, abcDNA, gcode, bgAA, bgDNA, M, L, N);
//  utest_fwdback(r, abc, bg, 1, L, 10);
//  utest_fwdback(r, abc, bg, M, 1, 10);

  esl_alphabet_Destroy(abcDNA);
  esl_alphabet_Destroy(abcAA);
  p7_bg_Destroy(bgDNA);
  p7_bg_Destroy(bgAA);
  esl_gencode_Destroy(gcode);

  esl_getopts_Destroy(go);
  esl_randomness_Destroy(r);
  return eslOK;
}
#endif /*p7FWDBACKFS_TESTDRIVE*/


/*--------------------- end, test driver ------------------------*/



/*****************************************************************
 * 5. Example
 *****************************************************************/

