/* SSE implementation of Frameshift Aware Forward and Backward algorithms.
 *
 * Both profile and DP matrix are striped and interleaved, for fast
 * SIMD vector operations. Calculations are in probability space
 * (scaled odds ratios, actually) rather than log probabilities,
 * allowing fast multiply/add operations rather than slow Logsum()
 * calculations. Sparse rescaling is used to achieve full dynamic
 * range of scores.
 *
 * The Forward and Backward implementations may be used either in a
 * full O(ML) mode that keeps an entire DP matrix, or in a O(M+L)
 * linear memory "parsing" mode that only keeps one row of memory for
 * the main MDI states and one column 0..L for the special states
 * B,E,N,C,J. Keeping a full matrix allows subsequent stochastic
 * traceback or posterior decoding of any state. In parsing mode, we
 * can do posterior decoding on the special states and determine
 * regions of the target sequence that are generated by the
 * nonhomology states (NCJ) versus not -- thus, identifying where
 * high-probability "regions" are, the first step of identifying the
 * domain structure of a target sequence.
 *
 * Contents:
 *   1. Forward/Backward 
 *   2. Benchmark driver.
 *   3. Unit tests.
 *   4. Test driver.
 *   5. Example.
 *
 * SRE, Thu Jul 31 08:43:20 2008 [Janelia]
 */
#include "p7_config.h"

#include <stdio.h>
#include <math.h>

#include <xmmintrin.h>		/* SSE  */
#include <emmintrin.h>		/* SSE2 */

#include "easel.h"
#include "esl_alphabet.h"
#include "esl_gencode.h"
#include "esl_sse.h"

#include "hmmer.h"
#include "impl_sse.h"

/* IVX intermediate matrix access: [slot 0..p7P_3CODONS-1][stripe 0..Q-1] */
#define IVX(slot, q) (ivxf[(slot)*Q + (q)])

/*****************************************************************
 * 1. Forward/Backward
 *****************************************************************/

/* Function:  p7_ForwardParser_Frameshift_3Codons_SSE()
 * Synopsis:  SSE-accelerated frameshift-aware Forward algorithm, 3 codon lengths, linear memory.
 *
 * Purpose:   The Forward dynamic programming algorithm for frameshift-aware
 *            translated comparison between a nucleotide sequence and a
 *            frameshift-aware codon HMM, using three codon lengths (2, 3, 4
 *            nucleotides), implemented with SIMD parallelism and sparse
 *            rescaling for full floating-point dynamic range.
 *
 *            Given a digital nucleotide sequence <dsq> of length <L>, an
 *            optimized frameshift profile <om_fs> (codon_lengths == 3), and a
 *            DP matrix <ox> allocated for at least PARSER_ROWS_FWD MDI rows
 *            and L special-state rows, computes the Forward probability of the
 *            sequence given the model and returns the Forward score in nats in
 *            <*opt_sc>.
 *
 *            Calculations are in probability space (odds ratios) with sparse
 *            rescaling. The profile must be in local alignment mode.
 *
 *            The intermediate value matrix (IVX) is allocated locally as
 *            p7P_3CODONS circular rows of Q SIMD vectors each. MDI rows in
 *            <ox> are used in a circular fashion (PARSER_ROWS_FWD = 4 rows).
 *            Special states are maintained in scalar circular buffers of size
 *            PARSER_ROWS_FWD; only the scale factors and final special state
 *            values are written to ox->xmx.
 *
 *            The caller must allocate <ox> with at least PARSER_ROWS_FWD
 *            valid MDI rows (ox->validR >= PARSER_ROWS_FWD) and L+1 X-rows
 *            (ox->allocXR > L).
 *
 * Args:      dsq    - nucleotide sequence in digitized form, 1..L
 *            gcode  - genetic code table (for nucleotide alphabet)
 *            L      - length of dsq
 *            om_fs  - optimized frameshift profile (codon_lengths must be 3)
 *            ox     - DP matrix with PARSER_ROWS_FWD MDI rows and L X rows
 *            opt_sc - optRETURN: Forward score in nats
 *
 * Returns:   <eslOK> on success.
 *
 * Throws:    <eslEINVAL> if profile or matrix allocation is incorrect.
 *            <eslERANGE> if score overflows or underflows.
 *            In either case, <*opt_sc> is undefined.
 */
int
p7_ForwardParser_Frameshift_3Codons_SSE(const ESL_DSQ *dsq, const ESL_GENCODE *gcode, int L,
                                         const P7_FS_OPROFILE *om_fs, P7_OMX *ox, float *opt_sc)
{
  register __m128 mpv2, dpv2, ipv2;   /* right-shifted prev2 row MDI for BM/MM/IM/DM   */
  register __m128 sv;                 /* temporary IVX accumulator                      */
  register __m128 msv;                /* M state accumulator for current position       */
  register __m128 dcv;                /* delayed D(i,q+1) = M(i,q)*tMD carry value     */
  register __m128 xEv;                /* E state sum: horizontal reduce to scalar xE    */
  register __m128 xBv2;               /* splatted B(i-2) for B->Mk transitions          */
  __m128   zerov;                     /* splatted 0.0                                   */
  float    xN, xE, xB, xC, xJ;        /* special state values at position i             */
  float    xN_buf[PARSER_ROWS_FWD];   /* circular buffer: N(i) at slot i%PARSER_ROWS_FWD */
  float    xB_buf[PARSER_ROWS_FWD];   /* circular buffer: B(i) at slot i%PARSER_ROWS_FWD */
  float    xJ_buf[PARSER_ROWS_FWD];   /* circular buffer: J(i) at slot i%PARSER_ROWS_FWD */
  float    xC_buf[PARSER_ROWS_FWD];   /* circular buffer: C(i) at slot i%PARSER_ROWS_FWD */
  int      b, b2, b3;                 /* buffer slots for i, i-2, i-3                  */
  int      curr, prev2, prev3;        /* MDI row indices (circular mod PARSER_ROWS_FWD) */
  int      ivx_2, ivx_3, ivx_4;       /* IVX slot indices for rows at i, i-1, i-2      */
  __m128  *dpc, *dpp2, *dpp3;         /* MDI DP row pointers                            */
  __m128  *tp;                        /* steps through om_fs->tfv transitions           */
  __m128  *ivxf     = NULL;           /* IVX intermediate matrix [slot*Q + q]           */
  __m128  *ivxf_mem = NULL;           /* unaligned alloc backing ivxf                   */
  int      Q = p7O_NQF(om_fs->M);     /* number of SIMD float stripes                   */
  int      i, q, j, r;
  int      c2, c3, c4;                /* codon emission table indices                   */
  int      u, v, w, x;                /* rolling nucleotide window for codon lookup      */
  int      status;

  /* Validate inputs */
  if (om_fs->codon_lengths != 3) ESL_EXCEPTION(eslEINVAL, "profile not allocated for 3 codon lengths");

#if eslDEBUGLEVEL > 0
  if (om_fs->M > ox->allocQ4*4)        ESL_EXCEPTION(eslEINVAL, "DP matrix allocated too small (too few columns)");
  if (ox->validR < PARSER_ROWS_FWD)    ESL_EXCEPTION(eslEINVAL, "DP matrix needs at least PARSER_ROWS_FWD MDI rows");
  if (L >= ox->allocXR)                ESL_EXCEPTION(eslEINVAL, "DP matrix allocated too small (too few X rows)");
  if (! p7_fs_oprofile_IsLocal(om_fs)) ESL_EXCEPTION(eslEINVAL, "Forward implementation assumes local alignment mode");
#endif

  ox->M  = om_fs->M;
  ox->L  = L;
  ox->has_own_scales = TRUE;
  ox->totscale       = 0.0;
  zerov = _mm_setzero_ps();

  /* Allocate and align IVX: p7P_3CODONS circular rows x Q stripes */
  ESL_ALLOC(ivxf_mem, sizeof(__m128) * p7P_3CODONS * Q + 15);
  ivxf = (__m128 *) (((unsigned long int) ivxf_mem + 15) & (~0xf));

  /* Zero-initialize all PARSER_ROWS_FWD MDI rows */
  for (r = 0; r < PARSER_ROWS_FWD; r++)
    for (q = 0; q < Q; q++)
      MMO(ox->dpf[r],q) = IMO(ox->dpf[r],q) = DMO(ox->dpf[r],q) = zerov;

  /* Zero-initialize all p7P_3CODONS IVX rows */
  for (r = 0; r < p7P_3CODONS; r++)
    for (q = 0; q < Q; q++)
      IVX(r, q) = zerov;

  /* Initialize circular special-state buffers.
   * Slots 0 and 1 correspond to positions i=0 and i=1.
   * N(0)=N(1)=1.0 (no N->N recursion before first complete codon).
   * B(0)=B(1)=T_NM. E=J=C=0 for all slots initially.
   */
  for (r = 0; r < PARSER_ROWS_FWD; r++)
    xN_buf[r] = xB_buf[r] = xJ_buf[r] = xC_buf[r] = 0.0f;
  xN_buf[0] = xN_buf[1] = 1.0f;
  xB_buf[0] = xB_buf[1] = om_fs->xf[p7O_N][p7O_MOVE];

  /* Write i=0 and i=1 specials to ox->xmx */
  ox->xmx[p7X_SCALE] = 1.0;
  ox->xmx[p7X_E]     = 0.0;
  ox->xmx[p7X_N]     = 1.0;
  ox->xmx[p7X_J]     = 0.0;
  ox->xmx[p7X_B]     = om_fs->xf[p7O_N][p7O_MOVE];
  ox->xmx[p7X_C]     = 0.0;
  ox->xmx[1*p7X_NXCELLS+p7X_SCALE] = 1.0;
  ox->xmx[1*p7X_NXCELLS+p7X_E]     = 0.0;
  ox->xmx[1*p7X_NXCELLS+p7X_N]     = 1.0;
  ox->xmx[1*p7X_NXCELLS+p7X_J]     = 0.0;
  ox->xmx[1*p7X_NXCELLS+p7X_B]     = om_fs->xf[p7O_N][p7O_MOVE];
  ox->xmx[1*p7X_NXCELLS+p7X_C]     = 0.0;

  /* Initialize nucleotide rolling window.
   * u=v=placeholder (positions before sequence start).
   * w=dsq[1], x=dsq[2] for the i=2 initialization.
   */
  u = v = p7P_MAXCODONS3;
  if (esl_abc_XIsCanonical(gcode->nt_abc, dsq[1])) w = dsq[1]; else w = p7P_MAXCODONS3;
  if (esl_abc_XIsCanonical(gcode->nt_abc, dsq[2])) x = dsq[2]; else x = p7P_MAXCODONS3;

  /*----------------------------------------------------------------
   * Initialization: i=2
   * Only length-2 quasi-codon (c2 = dsq[1..2]) contributes.
   * IVX(ivx_2) comes from B(0)*BM only (prev2=row0 MDI are all 0).
   * IVX(ivx_3), IVX(ivx_4) are all zero (just initialized).
   * I(2,k) = 0 (prev3=row3 MDI are all zero).
   *----------------------------------------------------------------*/
  i = 2;
  c2 = p7P_CODON2_FS3(w, x); c2 = p7P_MINIDX(c2, p7P_DEGEN3_QC1);

  curr  = 2;  /* i % PARSER_ROWS_FWD */
  prev2 = 0;  /* (i-2) % PARSER_ROWS_FWD */
  prev3 = 3;  /* (i-3+PARSER_ROWS_FWD) % PARSER_ROWS_FWD; all zeros */
  ivx_2 = 2;  /* i % p7P_3CODONS */
  ivx_3 = 1;  /* (i-1) % p7P_3CODONS; all zeros */
  ivx_4 = 0;  /* (i-2) % p7P_3CODONS; all zeros */

  dpc  = ox->dpf[curr];
  dpp2 = ox->dpf[prev2];   /* all zeros */
  dpp3 = ox->dpf[prev3];   /* all zeros */

  xBv2 = _mm_set1_ps(xB_buf[0]);   /* B(0) */
  tp   = om_fs->tfv;
  dcv  = zerov;
  xEv  = zerov;
  /* Right-shifts of all-zero row 0 are all zero */
  mpv2 = dpv2 = ipv2 = zerov;

  for (q = 0; q < Q; q++)
    {
      /* IVX(ivx_2,q) = B(0)*BM[k-1] only; MM/IM/DM are zero */
      sv  =                _mm_mul_ps(xBv2, *tp); tp++;   /* BM */
      sv  = _mm_add_ps(sv, _mm_mul_ps(mpv2, *tp)); tp++;  /* MM (= 0) */
      sv  = _mm_add_ps(sv, _mm_mul_ps(ipv2, *tp)); tp++;  /* IM (= 0) */
      sv  = _mm_add_ps(sv, _mm_mul_ps(dpv2, *tp)); tp++;  /* DM (= 0) */
      IVX(ivx_2, q) = sv;

      /* M(2,q) = IVX(ivx_2,q) * R2(q); IVX(ivx_3,ivx_4) are zero */
      msv = _mm_mul_ps(sv, om_fs->rfv[c2][q]);
      xEv = _mm_add_ps(xEv, msv);

      MMO(dpc, q) = msv;
      DMO(dpc, q) = dcv;

      dcv = _mm_mul_ps(msv, *tp); tp++;   /* MD: carry M(i,q)*tMD into D(i,q+1) */

      /* I(2,q) = 0 (dpp3 is all zeros) */
      IMO(dpc, q) = zerov;
      tp += 2;  /* skip MI, II */
    }

  /* DD paths for row 2 */
  dcv        = esl_sse_rightshiftz_float(dcv);
  DMO(dpc,0) = zerov;
  tp         = om_fs->tfv + 7*Q;
  for (q = 0; q < Q; q++)
    {
      DMO(dpc, q) = _mm_add_ps(dcv, DMO(dpc, q));
      dcv         = _mm_mul_ps(DMO(dpc, q), *tp); tp++;
    }
  if (om_fs->M < 100)
    {
      for (j = 1; j < 4; j++)
        {
          dcv = esl_sse_rightshiftz_float(dcv);
          tp  = om_fs->tfv + 7*Q;
          for (q = 0; q < Q; q++)
            {
              DMO(dpc, q) = _mm_add_ps(dcv, DMO(dpc, q));
              dcv         = _mm_mul_ps(dcv, *tp); tp++;
            }
        }
    }
  else
    {
      for (j = 1; j < 4; j++)
        {
          register __m128 cv;
          dcv = esl_sse_rightshiftz_float(dcv);
          tp  = om_fs->tfv + 7*Q;
          cv  = zerov;
          for (q = 0; q < Q; q++)
            {
              sv          = _mm_add_ps(dcv, DMO(dpc, q));
              cv          = _mm_or_ps(cv, _mm_cmpgt_ps(sv, DMO(dpc, q)));
              DMO(dpc, q) = sv;
              dcv         = _mm_mul_ps(dcv, *tp); tp++;
            }
          if (! _mm_movemask_ps(cv)) break;
        }
    }

  /* Add D contributions and horizontal-sum xEv → xE */
  for (q = 0; q < Q; q++) xEv = _mm_add_ps(DMO(dpc, q), xEv);
  xEv = _mm_add_ps(xEv, _mm_shuffle_ps(xEv, xEv, _MM_SHUFFLE(0, 3, 2, 1)));
  xEv = _mm_add_ps(xEv, _mm_shuffle_ps(xEv, xEv, _MM_SHUFFLE(1, 0, 3, 2)));
  _mm_store_ss(&xE, xEv);

  /* Special states at i=2: N is held constant at 1.0 (no N->N recursion yet) */
  xN = 1.0f;
  xJ = xE * om_fs->xf[p7O_E][p7O_LOOP];
  xC = xE * om_fs->xf[p7O_E][p7O_MOVE];
  xB = xN * om_fs->xf[p7O_N][p7O_MOVE] + xJ * om_fs->xf[p7O_J][p7O_MOVE];

  /* Sparse rescaling at i=2 */
  if (xE > 1.0e4f)
    {
      float scale_factor = 1.0f / xE;
      xN *= scale_factor; xJ *= scale_factor; xC *= scale_factor; xB *= scale_factor;
      xEv = _mm_set1_ps(scale_factor);
      for (r = 0; r < PARSER_ROWS_FWD; r++)
        for (q = 0; q < Q; q++)
          {
            MMO(ox->dpf[r], q) = _mm_mul_ps(MMO(ox->dpf[r], q), xEv);
            DMO(ox->dpf[r], q) = _mm_mul_ps(DMO(ox->dpf[r], q), xEv);
            IMO(ox->dpf[r], q) = _mm_mul_ps(IMO(ox->dpf[r], q), xEv);
          }
      for (r = 0; r < p7P_3CODONS; r++)
        for (q = 0; q < Q; q++)
          IVX(r, q) = _mm_mul_ps(IVX(r, q), xEv);
      for (r = 0; r < PARSER_ROWS_FWD; r++)
        {
          xN_buf[r] *= scale_factor; xB_buf[r] *= scale_factor;
          xJ_buf[r] *= scale_factor; xC_buf[r] *= scale_factor;
        }
      ox->xmx[2*p7X_NXCELLS+p7X_SCALE] = xE;
      ox->totscale += log(xE);
      xE = 1.0f;
    }
  else ox->xmx[2*p7X_NXCELLS+p7X_SCALE] = 1.0f;

  /* Store i=2 specials to circular buffers and ox->xmx */
  xN_buf[2] = xN; xB_buf[2] = xB; xJ_buf[2] = xJ; xC_buf[2] = xC;
  ox->xmx[2*p7X_NXCELLS+p7X_E] = xE;
  ox->xmx[2*p7X_NXCELLS+p7X_N] = xN;
  ox->xmx[2*p7X_NXCELLS+p7X_J] = xJ;
  ox->xmx[2*p7X_NXCELLS+p7X_B] = xB;
  ox->xmx[2*p7X_NXCELLS+p7X_C] = xC;

  /*----------------------------------------------------------------
   * Main recurrence: i = 3..L
   *
   * M(i,k) = [ B(i-2)*BM(k-1) + M(i-2,k-1)*MM(k-1)
   *            + I(i-2,k-1)*IM(k-1) + D(i-2,k-1)*DM(k-1) ] * R2(k)   [2-nt codon]
   *          + IVX(i-1,k) * R3(k)                                       [3-nt codon]
   *          + IVX(i-2,k) * R4(k)                                       [4-nt codon]
   *
   * where IVX(i,k) holds the pre-emission entry value from row i
   * (computed at iteration i+1 as the i-2 contribution for that row).
   *
   * I(i,k) = M(i-3,k)*MI(k) + I(i-3,k)*II(k)    (same stripe, no right-shift)
   * D(i,k) = M(i,k-1)*MD(k-1) + D(i,k-1)*DD(k-1) (within-row serialization)
   *
   * N(i) = N(i-3)*T_NL
   * J(i) = J(i-3)*T_JL + E(i)*T_EL
   * C(i) = C(i-3)*T_CL + E(i)*T_EM
   * B(i) = N(i)*T_NM + J(i)*T_JM
   *
   * Special states reference i-3 buffers; IVX and M->D use i-2 (prev2).
   *----------------------------------------------------------------*/
  for (i = 3; i <= L; i++)
    {
      /* Advance nucleotide window */
      u = v; v = w; w = x;
      if (esl_abc_XIsCanonical(gcode->nt_abc, dsq[i])) x = dsq[i]; else x = p7P_MAXCODONS3;

      /* Look up codon emission table indices */
      c2 = p7P_CODON2_FS3(w, x); c2 = p7P_MINIDX(c2, p7P_DEGEN3_QC1);
      c3 = p7P_CODON3_FS3(v, w, x); c3 = p7P_MINIDX(c3, p7P_DEGEN3_C);
      c4 = p7P_CODON4_FS3(u, v, w, x); c4 = p7P_MINIDX(c4, p7P_DEGEN3_QC1);

      /* Circular MDI row indices */
      curr  =     i               % PARSER_ROWS_FWD;
      prev2 = ((i-2) % PARSER_ROWS_FWD + PARSER_ROWS_FWD) % PARSER_ROWS_FWD;
      prev3 = ((i-3) % PARSER_ROWS_FWD + PARSER_ROWS_FWD) % PARSER_ROWS_FWD;

      /* IVX slot indices */
      ivx_2 =     i               % p7P_3CODONS;
      ivx_3 = ((i-1) % p7P_3CODONS + p7P_3CODONS) % p7P_3CODONS;
      ivx_4 = ((i-2) % p7P_3CODONS + p7P_3CODONS) % p7P_3CODONS;

      /* Circular special-state buffer indices */
      b  =     i               % PARSER_ROWS_FWD;
      b2 = ((i-2) % PARSER_ROWS_FWD + PARSER_ROWS_FWD) % PARSER_ROWS_FWD;
      b3 = ((i-3) % PARSER_ROWS_FWD + PARSER_ROWS_FWD) % PARSER_ROWS_FWD;

      dpc  = ox->dpf[curr];
      dpp2 = ox->dpf[prev2];
      dpp3 = ox->dpf[prev3];

      /* Right-shift prev2 MDI for (k-1) indexing in BM/MM/IM/DM transitions */
      mpv2 = esl_sse_rightshiftz_float(MMO(dpp2, Q-1));
      dpv2 = esl_sse_rightshiftz_float(DMO(dpp2, Q-1));
      ipv2 = esl_sse_rightshiftz_float(IMO(dpp2, Q-1));

      xBv2 = _mm_set1_ps(xB_buf[b2]);   /* B(i-2) splatted */
      tp   = om_fs->tfv;
      dcv  = zerov;
      xEv  = zerov;

      for (q = 0; q < Q; q++)
        {
          /* IVX(ivx_2,q): pre-emission entry from row i-2 into match position k */
          sv  =                _mm_mul_ps(xBv2, *tp); tp++;   /* BM: B(i-2) -> Mk  */
          sv  = _mm_add_ps(sv, _mm_mul_ps(mpv2, *tp)); tp++;  /* MM: M(i-2,k-1)    */
          sv  = _mm_add_ps(sv, _mm_mul_ps(ipv2, *tp)); tp++;  /* IM: I(i-2,k-1)    */
          sv  = _mm_add_ps(sv, _mm_mul_ps(dpv2, *tp)); tp++;  /* DM: D(i-2,k-1)    */
          IVX(ivx_2, q) = sv;

          /* M(i,k) = IVX(ivx_2)*R2 + IVX(ivx_3)*R3 + IVX(ivx_4)*R4 */
          msv =                _mm_mul_ps(sv,              om_fs->rfv[c2][q]);
          msv = _mm_add_ps(msv, _mm_mul_ps(IVX(ivx_3, q), om_fs->rfv[c3][q]));
          msv = _mm_add_ps(msv, _mm_mul_ps(IVX(ivx_4, q), om_fs->rfv[c4][q]));
          xEv = _mm_add_ps(xEv, msv);

          /* Update prev2 (k-1) values for next stripe q */
          mpv2 = MMO(dpp2, q);
          dpv2 = DMO(dpp2, q);
          ipv2 = IMO(dpp2, q);

          /* Store M(i,q); store delayed D(i,q) from previous q's carry */
          MMO(dpc, q) = msv;
          DMO(dpc, q) = dcv;

          /* Carry M(i,q)*tMD into D(i,q+1) */
          dcv = _mm_mul_ps(msv, *tp); tp++;   /* MD */

          /* I(i,k) = M(i-3,k)*MI + I(i-3,k)*II  (same stripe, no right-shift) */
          sv          =                _mm_mul_ps(MMO(dpp3, q), *tp); tp++;  /* MI */
          IMO(dpc, q) = _mm_add_ps(sv, _mm_mul_ps(IMO(dpp3, q), *tp)); tp++;  /* II */
        }

      /* DD paths: serialize D(i,k) = M(i,k-1)*MD + D(i,k-1)*DD
       * (same 4-pass serialization as forward_engine)
       */
      dcv        = esl_sse_rightshiftz_float(dcv);
      DMO(dpc,0) = zerov;
      tp         = om_fs->tfv + 7*Q;
      for (q = 0; q < Q; q++)
        {
          DMO(dpc, q) = _mm_add_ps(dcv, DMO(dpc, q));
          dcv         = _mm_mul_ps(DMO(dpc, q), *tp); tp++;
        }
      if (om_fs->M < 100)
        {
          for (j = 1; j < 4; j++)
            {
              dcv = esl_sse_rightshiftz_float(dcv);
              tp  = om_fs->tfv + 7*Q;
              for (q = 0; q < Q; q++)
                {
                  DMO(dpc, q) = _mm_add_ps(dcv, DMO(dpc, q));
                  dcv         = _mm_mul_ps(dcv, *tp); tp++;
                }
            }
        }
      else
        {
          for (j = 1; j < 4; j++)
            {
              register __m128 cv;
              dcv = esl_sse_rightshiftz_float(dcv);
              tp  = om_fs->tfv + 7*Q;
              cv  = zerov;
              for (q = 0; q < Q; q++)
                {
                  sv          = _mm_add_ps(dcv, DMO(dpc, q));
                  cv          = _mm_or_ps(cv, _mm_cmpgt_ps(sv, DMO(dpc, q)));
                  DMO(dpc, q) = sv;
                  dcv         = _mm_mul_ps(dcv, *tp); tp++;
                }
              if (! _mm_movemask_ps(cv)) break;
            }
        }

      /* Add D contributions to xEv, horizontal-sum → scalar xE */
      for (q = 0; q < Q; q++) xEv = _mm_add_ps(DMO(dpc, q), xEv);
      xEv = _mm_add_ps(xEv, _mm_shuffle_ps(xEv, xEv, _MM_SHUFFLE(0, 3, 2, 1)));
      xEv = _mm_add_ps(xEv, _mm_shuffle_ps(xEv, xEv, _MM_SHUFFLE(1, 0, 3, 2)));
      _mm_store_ss(&xE, xEv);

      /* Special state recursions using i-3 circular buffer values */
      xN = xN_buf[b3] * om_fs->xf[p7O_N][p7O_LOOP];
      xJ = xJ_buf[b3] * om_fs->xf[p7O_J][p7O_LOOP] + xE * om_fs->xf[p7O_E][p7O_LOOP];
      xC = xC_buf[b3] * om_fs->xf[p7O_C][p7O_LOOP] + xE * om_fs->xf[p7O_E][p7O_MOVE];
      xB = xN         * om_fs->xf[p7O_N][p7O_MOVE]  + xJ * om_fs->xf[p7O_J][p7O_MOVE];

      /* Sparse rescaling: when xE exceeds threshold, rescale ALL rows and buffers
       * so that all values remain on the same relative scale.
       * We must rescale all PARSER_ROWS_FWD MDI rows, all p7P_3CODONS IVX rows,
       * and all PARSER_ROWS_FWD entries of every circular special-state buffer.
       */
      if (xE > 1.0e4f)
        {
          float scale_factor = 1.0f / xE;
          xN *= scale_factor; xJ *= scale_factor; xC *= scale_factor; xB *= scale_factor;
          xEv = _mm_set1_ps(scale_factor);
          for (r = 0; r < PARSER_ROWS_FWD; r++)
            for (q = 0; q < Q; q++)
              {
                MMO(ox->dpf[r], q) = _mm_mul_ps(MMO(ox->dpf[r], q), xEv);
                DMO(ox->dpf[r], q) = _mm_mul_ps(DMO(ox->dpf[r], q), xEv);
                IMO(ox->dpf[r], q) = _mm_mul_ps(IMO(ox->dpf[r], q), xEv);
              }
          for (r = 0; r < p7P_3CODONS; r++)
            for (q = 0; q < Q; q++)
              IVX(r, q) = _mm_mul_ps(IVX(r, q), xEv);
          for (r = 0; r < PARSER_ROWS_FWD; r++)
            {
              xN_buf[r] *= scale_factor; xB_buf[r] *= scale_factor;
              xJ_buf[r] *= scale_factor; xC_buf[r] *= scale_factor;
            }
          ox->xmx[i*p7X_NXCELLS+p7X_SCALE] = xE;
          ox->totscale += log(xE);
          xE = 1.0f;
        }
      else ox->xmx[i*p7X_NXCELLS+p7X_SCALE] = 1.0f;

      /* Store specials to circular buffers and ox->xmx */
      xN_buf[b] = xN; xB_buf[b] = xB; xJ_buf[b] = xJ; xC_buf[b] = xC;
      ox->xmx[i*p7X_NXCELLS+p7X_E] = xE;
      ox->xmx[i*p7X_NXCELLS+p7X_N] = xN;
      ox->xmx[i*p7X_NXCELLS+p7X_J] = xJ;
      ox->xmx[i*p7X_NXCELLS+p7X_B] = xB;
      ox->xmx[i*p7X_NXCELLS+p7X_C] = xC;
    } /* end main loop i=3..L */

  /* Final score: C->T transition.
   * Sequence ends after L nucleotides, which may complete a 2-, 3-, or 4-nt
   * codon at positions L, L-1, or L-2 respectively (relative to the last
   * codon start). Sum C-state contributions from those three end positions.
   * All xC_buf values are on the same scale (guaranteed by global rescaling).
   */
  {
    float xCL   = xC_buf[   L    % PARSER_ROWS_FWD];
    float xCLm1 = xC_buf[((L-1) % PARSER_ROWS_FWD + PARSER_ROWS_FWD) % PARSER_ROWS_FWD];
    float xCLm2 = xC_buf[((L-2) % PARSER_ROWS_FWD + PARSER_ROWS_FWD) % PARSER_ROWS_FWD];
    float xCtot = xCL
                + xCLm1 * om_fs->xf[p7O_C][p7O_LOOP]
                + xCLm2 * om_fs->xf[p7O_C][p7O_LOOP];

    if      (isnan(xCtot))           ESL_EXCEPTION(eslERANGE, "forward score is NaN");
    else if (L > 2 && xCtot == 0.0f) ESL_EXCEPTION(eslERANGE, "forward score underflow (is 0.0)");
    else if (isinf(xCtot) == 1)      ESL_EXCEPTION(eslERANGE, "forward score overflow (is infinity)");

    if (opt_sc != NULL)
      *opt_sc = ox->totscale + logf(xCtot * om_fs->xf[p7O_C][p7O_MOVE]);
  }

  free(ivxf_mem);
  return eslOK;

 ERROR:
  if (ivxf_mem) free(ivxf_mem);
  return status;
}



/* Function:  p7_BackwardParser_Frameshift_3Codons_SSE()
 * Synopsis:  SSE-accelerated frameshift-aware Backward algorithm, 3 codon lengths, linear memory.
 *
 * Purpose:   The Backward dynamic programming algorithm for frameshift-aware
 *            translated comparison between a nucleotide sequence and a
 *            frameshift-aware codon HMM, using three codon lengths (2, 3, 4
 *            nucleotides), implemented with SIMD parallelism.
 *
 *            Mirrors p7_BackwardParser_Frameshift_3Codons() in probability
 *            space with sparse rescaling, using scale factors from the filled
 *            Forward matrix <fwd>.
 *
 *            Caller must allocate <ox> with at least PARSER_ROWS_BWD valid MDI
 *            rows (ox->validR >= PARSER_ROWS_BWD) and L+1 X-rows.
 *
 * Args:      dsq    - nucleotide sequence in digitized form, 1..L
 *            gcode  - genetic code table (for nucleotide alphabet)
 *            L      - length of dsq
 *            om_fs  - optimized frameshift profile (codon_lengths must be 3)
 *            fwd    - filled Forward DP matrix, for sparse scale factors
 *            ox     - RETURN: Backward DP matrix (PARSER_ROWS_BWD MDI rows, L X rows)
 *            opt_sc - optRETURN: Backward score in nats
 *
 * Returns:   <eslOK> on success.
 *
 * Throws:    <eslEINVAL> if profile or matrix allocation is incorrect.
 *            <eslERANGE> if score overflows or underflows.
 */
int
p7_BackwardParser_Frameshift_3Codons_SSE(const ESL_DSQ *dsq, const ESL_GENCODE *gcode, int L,
                                          const P7_FS_OPROFILE *om_fs, const P7_OMX *fwd,
                                          P7_OMX *ox, float *opt_sc)
{
  register __m128 sv;                  /* temporary accumulator                           */
  register __m128 dcv;                 /* D(i,k+1) left-shift carry                      */
  register __m128 ivx_carry;           /* ivxf[k+1] left-shift carry                     */
  __m128   tmmv, timv, tdmv;          /* pre-shifted MM/IM/DM transitions for q=Q-1 iter */
  register __m128 xBv;                 /* accumulates B(i) = sum_k ivxf[k]*BM[k-1]       */
  register __m128 xEv;                 /* splatted E(i)                                   */
  __m128   zerov;                      /* splatted 0.0                                    */
  float    xN, xE, xB, xC, xJ;         /* special state values at position i              */
  float    xN_buf[PARSER_ROWS_BWD];    /* circular buffer: N(i) at i%PARSER_ROWS_BWD      */
  float    xB_buf[PARSER_ROWS_BWD];    /* circular buffer: B(i) at i%PARSER_ROWS_BWD      */
  float    xJ_buf[PARSER_ROWS_BWD];    /* circular buffer: J(i) at i%PARSER_ROWS_BWD      */
  float    xC_buf[PARSER_ROWS_BWD];    /* circular buffer: C(i) at i%PARSER_ROWS_BWD      */
  int      b, b3;                      /* buffer slots for i, i+3                         */
  int      curr, prev2, prev3, prev4;  /* MDI row indices (circular mod PARSER_ROWS_BWD)  */
  __m128  *dpc, *dpp2, *dpp3, *dpp4;   /* MDI DP row pointers                             */
  __m128  *tp7;                        /* steps backward through om_fs->tfv (7 per stripe)*/
  __m128  *tp_dd;                      /* steps backward through DD block                 */
  __m128  *tp_mm;                      /* stripe (q+1)%Q for rotated MM/IM/DM transitions */
  __m128  *ivxf     = NULL;            /* ivx intermediate values [q], recomputed each i  */
  __m128  *ivxf_mem = NULL;            /* unaligned alloc backing ivxf                    */
  int      Q = p7O_NQF(om_fs->M);      /* number of SIMD float stripes                    */
  int      i, q, j, r;
  int      c2, c3, c4;                 /* codon emission table indices                    */
  int      u, v, w, x;                 /* rolling nucleotide window (i+4..i+1)             */
  float    scale;                      /* fwd scale factor at row i                        */
  int      status;

  if (om_fs->codon_lengths != 3)
    ESL_EXCEPTION(eslEINVAL, "profile not allocated for 3 codon lengths");
#if eslDEBUGLEVEL > 0
  if (om_fs->M > ox->allocQ4*4)
    ESL_EXCEPTION(eslEINVAL, "DP matrix allocated too small (too few columns)");
  if (ox->validR < PARSER_ROWS_BWD)
    ESL_EXCEPTION(eslEINVAL, "DP matrix needs at least PARSER_ROWS_BWD MDI rows");
  if (L >= ox->allocXR)
    ESL_EXCEPTION(eslEINVAL, "DP matrix allocated too small (too few X rows)");
  if (! p7_fs_oprofile_IsLocal(om_fs))
    ESL_EXCEPTION(eslEINVAL, "Backward implementation assumes local alignment mode");
#endif

  ox->M              = om_fs->M;
  ox->L              = L;
  ox->has_own_scales = FALSE;
  ox->totscale       = 0.0;
  zerov = _mm_setzero_ps();

  /* Allocate and align ivxf: Q stripes (recomputed at each position i) */
  ESL_ALLOC(ivxf_mem, sizeof(__m128) * Q + 15);
  ivxf = (__m128 *) (((unsigned long int) ivxf_mem + 15) & (~0xf));

  /* Zero-initialize all PARSER_ROWS_BWD MDI rows */
  for (r = 0; r < PARSER_ROWS_BWD; r++)
    for (q = 0; q < Q; q++)
      MMO(ox->dpf[r],q) = IMO(ox->dpf[r],q) = DMO(ox->dpf[r],q) = zerov;

  /* Zero-initialize all circular special-state buffers */
  for (r = 0; r < PARSER_ROWS_BWD; r++)
    xN_buf[r] = xB_buf[r] = xJ_buf[r] = xC_buf[r] = 0.0f;

  /*----------------------------------------------------------------
   * Initialization: rows L and L-1
   * C(L)   = T_CM.  C(L-1) = T_CL * T_CM.
   * J=B=N=0. E = C * T_EM.  MDI: M=D=xE, I=0, DD+MD backward passes.
   * No ivxf or I(i+3) contributions (future rows are 0).
   *----------------------------------------------------------------*/
  for (i = L; i >= L-1; i--)
    {
      b   = i % PARSER_ROWS_BWD;
      curr = b;

      if      (i == L)   xC = om_fs->xf[p7O_C][p7O_MOVE];
      else if (i == L-1) xC = om_fs->xf[p7O_C][p7O_LOOP] * om_fs->xf[p7O_C][p7O_MOVE];

      xN = xB = xJ = 0.0f;
      xE = xC * om_fs->xf[p7O_E][p7O_MOVE];
      xEv = _mm_set1_ps(xE);

      dpc = ox->dpf[curr];
      for (q = 0; q < Q; q++)
        { MMO(dpc,q) = xEv; DMO(dpc,q) = xEv; IMO(dpc,q) = zerov; }

      /* DD backward passes: propagate D(i,k+1)*DD into D(i,k) */
      dcv    = esl_sse_leftshiftz_float(DMO(dpc,0));
      tp_dd  = om_fs->tfv + 8*Q - 1;
      for (q = Q-1; q >= 0; q--)
        { sv = _mm_mul_ps(dcv, *tp_dd); tp_dd--;
          DMO(dpc,q) = _mm_add_ps(DMO(dpc,q), sv); dcv = DMO(dpc,q); }
      dcv = sv;  /* passes 2-4 must extend chain contribution, not full D */
      for (j = 1; j < 4; j++)
        { dcv   = esl_sse_leftshiftz_float(dcv);
          tp_dd = om_fs->tfv + 8*Q - 1;
          for (q = Q-1; q >= 0; q--)
            { sv = _mm_mul_ps(dcv, *tp_dd); tp_dd--;
              DMO(dpc,q) = _mm_add_ps(DMO(dpc,q), sv);
              dcv = _mm_mul_ps(dcv, *(tp_dd+1)); } }

      /* MD correction: D(i,k+1)*MD(k) into M(i,k) */
      dcv  = esl_sse_leftshiftz_float(DMO(dpc,0));
      tp7  = om_fs->tfv + 7*Q - 3;   /* MD transition for stripe Q-1 */
      for (q = Q-1; q >= 0; q--)
        { MMO(dpc,q) = _mm_add_ps(MMO(dpc,q), _mm_mul_ps(dcv, *tp7)); tp7 -= 7;
          dcv = DMO(dpc,q); }

      /* Rescale using fwd scale factor */
      scale = fwd->xmx[i*p7X_NXCELLS+p7X_SCALE];
      ox->xmx[i*p7X_NXCELLS+p7X_SCALE] = scale;
      if (scale > 1.0f)
        { float sf = 1.0f / scale;
          xN *= sf; xJ *= sf; xC *= sf; xB *= sf; xE *= sf;
          xEv = _mm_set1_ps(sf);
          for (r = 0; r < PARSER_ROWS_BWD; r++)
            for (q = 0; q < Q; q++)
              { MMO(ox->dpf[r],q) = _mm_mul_ps(MMO(ox->dpf[r],q), xEv);
                DMO(ox->dpf[r],q) = _mm_mul_ps(DMO(ox->dpf[r],q), xEv);
                IMO(ox->dpf[r],q) = _mm_mul_ps(IMO(ox->dpf[r],q), xEv); }
          ox->totscale += log(scale); }

      xN_buf[b] = xN; xB_buf[b] = xB; xJ_buf[b] = xJ; xC_buf[b] = xC;
      ox->xmx[i*p7X_NXCELLS+p7X_E] = xE;
      ox->xmx[i*p7X_NXCELLS+p7X_N] = xN;
      ox->xmx[i*p7X_NXCELLS+p7X_J] = xJ;
      ox->xmx[i*p7X_NXCELLS+p7X_B] = xB;
      ox->xmx[i*p7X_NXCELLS+p7X_C] = xC;

#if eslDEBUGLEVEL > 0
      if (ox->debugging) p7_omx_DumpFBRow_FS(ox, TRUE, i, curr, 9, 4, xE, xN, xJ, xB, xC);
#endif
    }

  /*----------------------------------------------------------------
   * Initialization: row L-2
   * C(L-2) = T_CL * T_CM (special case per scalar).
   * ivxf[q] = M(L, q) * R2 only (prev3=L+1 and prev4=L+2 are zero).
   * I(i+3) = I(L+1) = 0.
   *----------------------------------------------------------------*/
  /* Set up nucleotide window for codon lookup at i=L-2.
   * The backward algorithm reads dsq[i+1..i+4]: u=dsq[i+4], v=dsq[i+3], w=dsq[i+2], x=dsq[i+1].
   * At i=L-2: i+1=L-1, i+2=L, i+3=L+1 (beyond), i+4=L+2 (beyond). */
  u = v = p7P_MAXCODONS3;  /* placeholders for positions beyond L */
  if (esl_abc_XIsCanonical(gcode->nt_abc, dsq[L]))   w = dsq[L];   else w = p7P_MAXCODONS3;
  if (esl_abc_XIsCanonical(gcode->nt_abc, dsq[L-1])) x = dsq[L-1]; else x = p7P_MAXCODONS3;

  i    = L-2;
  b    = i % PARSER_ROWS_BWD;
  curr =  i    % PARSER_ROWS_BWD;
  prev2 = (i+2) % PARSER_ROWS_BWD;   /* = L % 6 */

  c2 = p7P_CODON2_FS3(x, w); c2 = p7P_MINIDX(c2, p7P_DEGEN3_QC1);

  dpc  = ox->dpf[curr];
  dpp2 = ox->dpf[prev2];

  /* ivxf[q] = M(i+2=L, q) * R2 */
  for (q = 0; q < Q; q++)
    ivxf[q] = _mm_mul_ps(MMO(dpp2,q), om_fs->rfv[c2][q]);

  /* B(L-2) = sum_k ivxf[k] * BM(k-1) */
  xBv = zerov;
  tp7 = om_fs->tfv;
  for (q = 0; q < Q; q++) { xBv = _mm_add_ps(xBv, _mm_mul_ps(ivxf[q], *tp7)); tp7 += 7; }
  xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(0,3,2,1)));
  xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(1,0,3,2)));
  _mm_store_ss(&xB, xBv);

  xC = om_fs->xf[p7O_C][p7O_LOOP] * om_fs->xf[p7O_C][p7O_MOVE];
  xJ = xB * om_fs->xf[p7O_J][p7O_MOVE];
  xN = xB * om_fs->xf[p7O_N][p7O_MOVE];
  xE = xJ * om_fs->xf[p7O_E][p7O_LOOP] + xC * om_fs->xf[p7O_E][p7O_MOVE];
  xEv = _mm_set1_ps(xE);

  /* MDI: init M=D=xE, I=0 */
  for (q = 0; q < Q; q++) { MMO(dpc,q) = xEv; DMO(dpc,q) = xEv; IMO(dpc,q) = zerov; }

  /* Add ivx[k+1]*MM, ivx[k+1]*IM, ivx[k+1]*DM (backward pass with left-shift carry).
   * MM/IM/DM transitions are stored rotated (destination-aligned): for k in stripe q,
   * TSC(MM,k) is at stripe (q+1)%Q. For the first iter (q=Q-1), the carry crosses a
   * stripe boundary so transitions at stripe 0 must also be left-shifted to align. */
  ivx_carry = esl_sse_leftshiftz_float(ivxf[0]);
  tmmv = esl_sse_leftshiftz_float(*(om_fs->tfv+1));  /* pre-shifted MM for first iter */
  timv = esl_sse_leftshiftz_float(*(om_fs->tfv+2));  /* pre-shifted IM for first iter */
  tdmv = esl_sse_leftshiftz_float(*(om_fs->tfv+3));  /* pre-shifted DM for first iter */
  tp_mm = om_fs->tfv;
  for (q = Q-1; q >= 0; q--)
    { MMO(dpc,q) = _mm_add_ps(MMO(dpc,q), _mm_mul_ps(ivx_carry, tmmv));
      IMO(dpc,q) = _mm_add_ps(IMO(dpc,q), _mm_mul_ps(ivx_carry, timv));
      DMO(dpc,q) = _mm_add_ps(DMO(dpc,q), _mm_mul_ps(ivx_carry, tdmv));
      ivx_carry  = ivxf[q];
      tp_mm = (tp_mm == om_fs->tfv) ? om_fs->tfv + 7*(Q-1) : tp_mm - 7;
      tmmv = *(tp_mm+1);
      timv = *(tp_mm+2);
      tdmv = *(tp_mm+3); }

  /* DD passes + MD correction (same as init rows) */
  dcv   = esl_sse_leftshiftz_float(DMO(dpc,0));
  tp_dd = om_fs->tfv + 8*Q - 1;
  for (q = Q-1; q >= 0; q--)
    { sv = _mm_mul_ps(dcv, *tp_dd); tp_dd--;
      DMO(dpc,q) = _mm_add_ps(DMO(dpc,q), sv); dcv = DMO(dpc,q); }
  dcv = sv;  /* passes 2-4 must extend chain contribution, not full D */
  for (j = 1; j < 4; j++)
    { dcv = esl_sse_leftshiftz_float(dcv); tp_dd = om_fs->tfv + 8*Q - 1;
      for (q = Q-1; q >= 0; q--)
        { sv = _mm_mul_ps(dcv, *tp_dd); tp_dd--;
          DMO(dpc,q) = _mm_add_ps(DMO(dpc,q), sv);
          dcv = _mm_mul_ps(dcv, *(tp_dd+1)); } }
  dcv = esl_sse_leftshiftz_float(DMO(dpc,0));
  tp7 = om_fs->tfv + 7*Q - 3;
  for (q = Q-1; q >= 0; q--)
    { MMO(dpc,q) = _mm_add_ps(MMO(dpc,q), _mm_mul_ps(dcv, *tp7)); tp7 -= 7;
      dcv = DMO(dpc,q); }

  scale = fwd->xmx[i*p7X_NXCELLS+p7X_SCALE];
  ox->xmx[i*p7X_NXCELLS+p7X_SCALE] = scale;
  if (scale > 1.0f)
    { float sf = 1.0f / scale;
      xN *= sf; xJ *= sf; xC *= sf; xB *= sf; xE *= sf;
      xEv = _mm_set1_ps(sf);
      for (r = 0; r < PARSER_ROWS_BWD; r++)
        for (q = 0; q < Q; q++)
          { MMO(ox->dpf[r],q) = _mm_mul_ps(MMO(ox->dpf[r],q), xEv);
            DMO(ox->dpf[r],q) = _mm_mul_ps(DMO(ox->dpf[r],q), xEv);
            IMO(ox->dpf[r],q) = _mm_mul_ps(IMO(ox->dpf[r],q), xEv); }
      for (r = 0; r < PARSER_ROWS_BWD; r++)
        { xN_buf[r] *= sf; xB_buf[r] *= sf; xJ_buf[r] *= sf; xC_buf[r] *= sf; }
      ox->totscale += log(scale); }

  xN_buf[b] = xN; xB_buf[b] = xB; xJ_buf[b] = xJ; xC_buf[b] = xC;
  ox->xmx[i*p7X_NXCELLS+p7X_E] = xE;
  ox->xmx[i*p7X_NXCELLS+p7X_N] = xN;
  ox->xmx[i*p7X_NXCELLS+p7X_J] = xJ;
  ox->xmx[i*p7X_NXCELLS+p7X_B] = xB;
  ox->xmx[i*p7X_NXCELLS+p7X_C] = xC;

#if eslDEBUGLEVEL > 0
      if (ox->debugging) p7_omx_DumpFBRow_FS(ox, TRUE, i, curr, 9, 4, xE, xN, xJ, xB, xC);
#endif

  /*----------------------------------------------------------------
   * Main recurrence: i = L-3 down to 1
   *
   * ivxf[q] = M(i+2,q)*R2 + M(i+3,q)*R3 + M(i+4,q)*R4
   * B(i) = sum_k ivxf[k]*BM(k-1)
   * C(i) = C(i+3) * T_CL
   * J(i) = J(i+3) * T_JL + B(i) * T_JM
   * N(i) = N(i+3) * T_NL + B(i) * T_NM
   * E(i) = J(i)*T_EL + C(i)*T_EM
   * M(i,k) = E*esc + D(i,k+1)*MD + I(i+3,k)*MI + ivx[k+1]*MM
   * D(i,k) = E*esc + D(i,k+1)*DD + ivx[k+1]*DM
   * I(i,k) =         I(i+3,k)*II + ivx[k+1]*IM
   *
   * For i=L-3: prev4=(L+1)%6 is all-zero → R4 contributes 0 (correct).
   * For i=L-4: prev3=(L-1)%6 has I=0 → I(i+3) contributes 0 (correct).
   *----------------------------------------------------------------*/
  for (i = L-3; i >= 1; i--)
    {
      u = v; v = w; w = x;
      if (esl_abc_XIsCanonical(gcode->nt_abc, dsq[i+1])) x = dsq[i+1]; else x = p7P_MAXCODONS3;

      c2 = p7P_CODON2_FS3(x, w); c2 = p7P_MINIDX(c2, p7P_DEGEN3_QC1);
      c3 = p7P_CODON3_FS3(x, w, v); c3 = p7P_MINIDX(c3, p7P_DEGEN3_C);
      c4 = p7P_CODON4_FS3(x, w, v, u); c4 = p7P_MINIDX(c4, p7P_DEGEN3_QC1);

      curr  =  i       % PARSER_ROWS_BWD;
      prev2 = (i+2)    % PARSER_ROWS_BWD;
      prev3 = (i+3)    % PARSER_ROWS_BWD;
      prev4 = (i+4)    % PARSER_ROWS_BWD;
      b     =  i       % PARSER_ROWS_BWD;
      b3    = (i+3)    % PARSER_ROWS_BWD;

      dpc  = ox->dpf[curr];
      dpp2 = ox->dpf[prev2];
      dpp3 = ox->dpf[prev3];
      dpp4 = ox->dpf[prev4];

      /* Phase 1: pre-compute ivxf[q] = M(i+2)*R2 + M(i+3)*R3 + M(i+4)*R4 */
      for (q = 0; q < Q; q++)
        ivxf[q] = _mm_add_ps(_mm_add_ps(
                    _mm_mul_ps(MMO(dpp2,q), om_fs->rfv[c2][q]),
                    _mm_mul_ps(MMO(dpp3,q), om_fs->rfv[c3][q])),
                    _mm_mul_ps(MMO(dpp4,q), om_fs->rfv[c4][q]));

      /* Phase 2: B(i) = sum_k ivxf[k] * BM(k-1), horizontal sum */
      xBv = zerov;
      tp7 = om_fs->tfv;
      for (q = 0; q < Q; q++) { xBv = _mm_add_ps(xBv, _mm_mul_ps(ivxf[q], *tp7)); tp7 += 7; }
      xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(0,3,2,1)));
      xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(1,0,3,2)));
      _mm_store_ss(&xB, xBv);

      /* Phase 3: special state recursions from i+3 buffers */
      xC = xC_buf[b3] * om_fs->xf[p7O_C][p7O_LOOP];
      xJ = xJ_buf[b3] * om_fs->xf[p7O_J][p7O_LOOP] + xB * om_fs->xf[p7O_J][p7O_MOVE];
      xN = xN_buf[b3] * om_fs->xf[p7O_N][p7O_LOOP] + xB * om_fs->xf[p7O_N][p7O_MOVE];
      xE = xJ * om_fs->xf[p7O_E][p7O_LOOP] + xC * om_fs->xf[p7O_E][p7O_MOVE];
      xEv = _mm_set1_ps(xE);

      /* Phase 4a: initialize M=D=xE, I=0 */
      for (q = 0; q < Q; q++)
        { MMO(dpc,q) = xEv; DMO(dpc,q) = xEv; IMO(dpc,q) = zerov; }

      /* Phase 4b: add I(i+3,k)*MI to M, I(i+3,k)*II to I (same stripe, forward pass) */
      tp7 = om_fs->tfv;
      for (q = 0; q < Q; q++)
        { MMO(dpc,q) = _mm_add_ps(MMO(dpc,q), _mm_mul_ps(IMO(dpp3,q), *(tp7+5)));  /* MI */
          IMO(dpc,q) = _mm_add_ps(IMO(dpc,q), _mm_mul_ps(IMO(dpp3,q), *(tp7+6)));  /* II */
          tp7 += 7; }

      /* Phase 4c: add ivx[k+1]*MM, ivx[k+1]*IM, ivx[k+1]*DM (backward pass).
       * MM/IM/DM transitions are stored rotated (destination-aligned): for k in stripe q,
       * TSC(MM,k) is at stripe (q+1)%Q. For the first iter (q=Q-1), the carry crosses a
       * stripe boundary so transitions at stripe 0 must also be left-shifted to align. */
      ivx_carry = esl_sse_leftshiftz_float(ivxf[0]);
      tmmv = esl_sse_leftshiftz_float(*(om_fs->tfv+1));  /* pre-shifted MM for first iter */
      timv = esl_sse_leftshiftz_float(*(om_fs->tfv+2));  /* pre-shifted IM for first iter */
      tdmv = esl_sse_leftshiftz_float(*(om_fs->tfv+3));  /* pre-shifted DM for first iter */
      tp_mm = om_fs->tfv;
      for (q = Q-1; q >= 0; q--)
        { MMO(dpc,q) = _mm_add_ps(MMO(dpc,q), _mm_mul_ps(ivx_carry, tmmv));
          IMO(dpc,q) = _mm_add_ps(IMO(dpc,q), _mm_mul_ps(ivx_carry, timv));
          DMO(dpc,q) = _mm_add_ps(DMO(dpc,q), _mm_mul_ps(ivx_carry, tdmv));
          ivx_carry  = ivxf[q];
          tp_mm = (tp_mm == om_fs->tfv) ? om_fs->tfv + 7*(Q-1) : tp_mm - 7;
          tmmv = *(tp_mm+1);
          timv = *(tp_mm+2);
          tdmv = *(tp_mm+3); }

      /* Phase 5: DD backward passes — propagate D(i,k+1)*DD into D(i,k)
       *          and then D(i,k+1)*MD into M(i,k)                                       */
      dcv   = esl_sse_leftshiftz_float(DMO(dpc,0));
      tp_dd = om_fs->tfv + 8*Q - 1;
      for (q = Q-1; q >= 0; q--)
        { sv = _mm_mul_ps(dcv, *tp_dd); tp_dd--;
          DMO(dpc,q) = _mm_add_ps(DMO(dpc,q), sv); dcv = DMO(dpc,q); }
      dcv = sv;  /* passes 2-4 must extend chain contribution, not full D */
      for (j = 1; j < 4; j++)
        { dcv = esl_sse_leftshiftz_float(dcv); tp_dd = om_fs->tfv + 8*Q - 1;
          for (q = Q-1; q >= 0; q--)
            { sv = _mm_mul_ps(dcv, *tp_dd); tp_dd--;
              DMO(dpc,q) = _mm_add_ps(DMO(dpc,q), sv);
              dcv = _mm_mul_ps(dcv, *(tp_dd+1)); } }

      /* Phase 6: MD correction — D(i,k+1)*MD(k) into M(i,k) */
      dcv = esl_sse_leftshiftz_float(DMO(dpc,0));
      tp7 = om_fs->tfv + 7*Q - 3;
      for (q = Q-1; q >= 0; q--)
        { MMO(dpc,q) = _mm_add_ps(MMO(dpc,q), _mm_mul_ps(dcv, *tp7)); tp7 -= 7;
          dcv = DMO(dpc,q); }

      /* Phase 7: sparse rescaling using fwd scale factor at row i */
      if (xB > 1.0e16f) ox->has_own_scales = TRUE;

      if (ox->has_own_scales) scale = (xB > 1.0e4f) ? xB : 1.0f;
      else                    scale = fwd->xmx[i*p7X_NXCELLS+p7X_SCALE];

      ox->xmx[i*p7X_NXCELLS+p7X_SCALE] = scale;
      if (scale > 1.0f)
        { float sf = 1.0f / scale;
          xN *= sf; xJ *= sf; xC *= sf; xB *= sf; xE *= sf;
          xEv = _mm_set1_ps(sf);
          for (r = 0; r < PARSER_ROWS_BWD; r++)
            for (q = 0; q < Q; q++)
              { MMO(ox->dpf[r],q) = _mm_mul_ps(MMO(ox->dpf[r],q), xEv);
                DMO(ox->dpf[r],q) = _mm_mul_ps(DMO(ox->dpf[r],q), xEv);
                IMO(ox->dpf[r],q) = _mm_mul_ps(IMO(ox->dpf[r],q), xEv); }
          for (r = 0; r < PARSER_ROWS_BWD; r++)
            { xN_buf[r] *= sf; xB_buf[r] *= sf; xJ_buf[r] *= sf; xC_buf[r] *= sf; }
          ox->totscale += log(scale); }

      xN_buf[b] = xN; xB_buf[b] = xB; xJ_buf[b] = xJ; xC_buf[b] = xC;
      ox->xmx[i*p7X_NXCELLS+p7X_E] = xE;
      ox->xmx[i*p7X_NXCELLS+p7X_N] = xN;
      ox->xmx[i*p7X_NXCELLS+p7X_J] = xJ;
      ox->xmx[i*p7X_NXCELLS+p7X_B] = xB;
      ox->xmx[i*p7X_NXCELLS+p7X_C] = xC;

#if eslDEBUGLEVEL > 0
      if (ox->debugging) p7_omx_DumpFBRow_FS(ox, TRUE, i, curr, 9, 4, xE, xN, xJ, xB, xC); /* logify=TRUE, <rowi>=L, width=9, precision=4*/
#endif 
    } /* end main loop i=L-3..1 */

  /*----------------------------------------------------------------
   * Termination: i=0
   * Only N and B are reachable.
   * ivxf[q] = M(2)*R2 + M(3)*R3 + M(4)*R4   (prev2=2, prev3=3, prev4=4)
   * B(0) = sum_k ivxf[k]*BM(k-1)
   * N(0) = N(3)*T_NL + B(0)*T_NM
   * Final score = N(0) + N(1) + N(2)   (probability space, all on same scale)
   *----------------------------------------------------------------*/
  u = v; v = w; w = x;
  if (esl_abc_XIsCanonical(gcode->nt_abc, dsq[1])) x = dsq[1]; else x = p7P_MAXCODONS3;

  c2 = p7P_CODON2_FS3(x, w); c2 = p7P_MINIDX(c2, p7P_DEGEN3_QC1);
  c3 = p7P_CODON3_FS3(x, w, v); c3 = p7P_MINIDX(c3, p7P_DEGEN3_C);
  c4 = p7P_CODON4_FS3(x, w, v, u); c4 = p7P_MINIDX(c4, p7P_DEGEN3_QC1);

  prev2 = 2 % PARSER_ROWS_BWD;
  prev3 = 3 % PARSER_ROWS_BWD;
  prev4 = 4 % PARSER_ROWS_BWD;

  dpp2 = ox->dpf[prev2];
  dpp3 = ox->dpf[prev3];
  dpp4 = ox->dpf[prev4];

  for (q = 0; q < Q; q++)
    ivxf[q] = _mm_add_ps(_mm_add_ps(
                _mm_mul_ps(MMO(dpp2,q), om_fs->rfv[c2][q]),
                _mm_mul_ps(MMO(dpp3,q), om_fs->rfv[c3][q])),
                _mm_mul_ps(MMO(dpp4,q), om_fs->rfv[c4][q]));

  xBv = zerov;
  tp7 = om_fs->tfv;
  for (q = 0; q < Q; q++) { xBv = _mm_add_ps(xBv, _mm_mul_ps(ivxf[q], *tp7)); tp7 += 7; }
  xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(0,3,2,1)));
  xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(1,0,3,2)));
  _mm_store_ss(&xB, xBv);

  xN = xN_buf[3 % PARSER_ROWS_BWD] * om_fs->xf[p7O_N][p7O_LOOP]
     + xB                           * om_fs->xf[p7O_N][p7O_MOVE];

  ox->xmx[p7X_B]     = xB;
  ox->xmx[p7X_N]     = xN;
  ox->xmx[p7X_J]     = 0.0f;
  ox->xmx[p7X_C]     = 0.0f;
  ox->xmx[p7X_E]     = 0.0f;
  ox->xmx[p7X_SCALE] = 1.0f;

#if eslDEBUGLEVEL > 0
      if (ox->debugging) p7_omx_DumpFBRow_FS(ox, TRUE, 0, 0, 9, 4, xE, xN, xJ, xB, xC); 
#endif

 /* Final score: log( N(0) + N(1) + N(2) ) + totscale.
  * The forward initializes N(0)=N(1)=N(2)=1 (three starting positions: 0, 1, or 2
  * leading nucleotides before the first codon). */
  {
    float xNtot = xN
                + xN_buf[1 % PARSER_ROWS_BWD]
                + xN_buf[2 % PARSER_ROWS_BWD];

    if      (isnan(xNtot))           ESL_EXCEPTION(eslERANGE, "backward score is NaN");
    else if (L > 0 && xNtot == 0.0f) ESL_EXCEPTION(eslERANGE, "backward score underflow (is 0.0)");
    else if (isinf(xNtot) == 1)      ESL_EXCEPTION(eslERANGE, "backward score overflow (is infinity)");

    if (opt_sc != NULL)
      *opt_sc = ox->totscale + logf(xNtot);
  }

  free(ivxf_mem);
  return eslOK;

 ERROR:
  if (ivxf_mem) free(ivxf_mem);
  return status;
}



/*-------------- end, forward/backward  -----------------*/

/*****************************************************************
 * 3. Unit tests.
 *****************************************************************/
#ifdef p7FWDBACK_FS_TESTDRIVE
#include "esl_random.h"
#include "esl_randomseq.h"

/*
 * compare to GForward() scores.
 */
static void
utest_fwdbackfs(ESL_RANDOMNESS *r, ESL_ALPHABET *abcAA, ESL_ALPHABET *abcDNA, ESL_GENCODE *gcode, P7_BG *bgAA, P7_BG *bgDNA, P7_CODONTABLE *codon_table, int M, int N)
{
  int  i,j;
  int  curr_L;
  char           *msg    = "forward/backward fs unit test failed";
  P7_HMM         *hmm    = NULL;
  P7_PROFILE     *gm     = p7_profile_Create(M, abcAA);
  P7_FS_PROFILE  *gm_fs3 = p7_profile_fs_Create(M, abcAA, 3);
  P7_FS_OPROFILE *om_fs3 = p7_fs_oprofile_Create(M, abcAA, 3); 
  ESL_SQ         *sq     = esl_sq_CreateDigital(abcAA); 
  ESL_DSQ        *dsq    = NULL;
  P7_TRACE       *tr     = p7_trace_Create();
  P7_OMX         *fwd    = p7_omx_Create(M, PARSER_ROWS_FWD, M);
  P7_OMX         *bwd    = p7_omx_Create(M, PARSER_ROWS_BWD, M);
  P7_GMX         *fgx    = p7_gmx_fs_Create(M, PARSER_ROWS_FWD, M, 0);
  P7_IVX         *iv     = p7_ivx_Create(M, p7P_3CODONS); 
  float tolerance, generic_tolerance;
  float fsc3, bsc3;
  float generic_fsc3;

  p7_FLogsumInit();
  if (p7_FLogsumError(-0.4, -0.5) > 0.0001) generic_tolerance = 1.0;  /* weaker test against generic   */
  else generic_tolerance = 0.001;   /* stronger test: FLogsum() is in slow exact mode. */
  tolerance = 0.0001;

  p7_hmm_Sample(r, M, abcAA, &hmm);
  p7_ProfileConfig(hmm, bgAA, gm, M, p7_LOCAL);
  p7_ProfileConfig_fs(hmm, bgAA, gcode, gm_fs3, M, p7_LOCAL);
  p7_fs_oprofile_Convert(gm_fs3, om_fs3);
  p7_fs_oprofile_ReconfigLength(om_fs3, M);

  while (N--)
    {
      
	  p7_ProfileEmit(r, hmm, gm, bgAA, sq, tr);
      curr_L = sq->n*3;
      
	  if(dsq != NULL) free(dsq);
      if ((dsq = malloc(sizeof(ESL_DSQ) *(curr_L+2))) == NULL)  esl_fatal("malloc failed");

	  j = 1;
	  for(i = 1; i <= sq->n; i++) {
        p7_codontable_GetCodon(codon_table, r, sq->dsq[i], dsq+j);
        j+=3;
      }

      p7_fs_oprofile_ReconfigLength(om_fs3, sq->n);
      p7_fs_ReconfigLength(gm_fs3, sq->n);

      p7_omx_GrowTo(fwd, M, PARSER_ROWS_FWD, curr_L);
      p7_gmx_fs_GrowTo(fgx, M, PARSER_ROWS_FWD, curr_L, 0);

      p7_ForwardParser_Frameshift_3Codons_SSE(dsq, gcode, curr_L, om_fs3, fwd, &fsc3);	  
	  p7_ForwardParser_Frameshift_3Codons(dsq, gcode, curr_L, gm_fs3, fgx, iv, &generic_fsc3);

      /* non simd Forward scores should approximate simd Forward scores,
       * with tolerance that depends on how logsum.c was compiled
       */
      if (fabs(fsc3-generic_fsc3) > generic_tolerance) esl_fatal(msg);

      p7_omx_GrowTo(bwd, M, PARSER_ROWS_BWD, curr_L);   
	  p7_BackwardParser_Frameshift_3Codons_SSE(dsq, gcode, curr_L, om_fs3, fwd, bwd, &bsc3);

      if (fabs(fsc3-bsc3) > tolerance) esl_fatal(msg); 
      

    }

  free(dsq);
  esl_sq_Destroy(sq);
  p7_hmm_Destroy(hmm);
  p7_omx_Destroy(fwd);
  p7_omx_Destroy(bwd);
  p7_gmx_Destroy(fgx);
  p7_ivx_Destroy(iv);
  p7_trace_Destroy(tr);
  p7_profile_Destroy(gm);
  p7_profile_fs_Destroy(gm_fs3);
  p7_fs_oprofile_Destroy(om_fs3);
}
#endif /*p7FWDBACK_FS_TESTDRIVE*/
/*---------------------- end, unit tests ------------------------*/



/*****************************************************************
 * 4. Test driver
 *****************************************************************/
#ifdef p7FWDBACK_FS_TESTDRIVE
/*
   gcc -g -Wall -msse2 -std=gnu99 -o fwdback_fs_utest -I.. -L.. -I../../easel -L../../easel -Dp7FWDBACK_FS_TESTDRIVE fwdback_fs.c -lhmmer -leasel -lm
   ./fwdback_fs_utest
 */
#include "p7_config.h"

#include "easel.h"
#include "esl_alphabet.h"
#include "esl_getopts.h"
#include "esl_random.h"

#include "hmmer.h"
#include "impl_sse.h"

static ESL_OPTIONS options[] = {
  /* name           type      default  env  range toggles reqs incomp  help                                       docgroup*/
  { "-h",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, NULL, "show brief help on version and usage",           0 },
  { "-s",        eslARG_INT,     "42", NULL, NULL,  NULL,  NULL, NULL, "set random number seed to <n>",                  0 },
  { "-M",        eslARG_INT,    "145", NULL, NULL,  NULL,  NULL, NULL, "size of random models to sample",                0 },
  { "-N",        eslARG_INT,    "100", NULL, NULL,  NULL,  NULL, NULL, "number of random sequences to sample",           0 },
  {  0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
};
static char usage[]  = "[-options]";
static char banner[] = "test driver for SSE Forward, Backward implementations";

int
main(int argc, char **argv)
{
  ESL_GETOPTS    *go     = p7_CreateDefaultApp(options, 0, argc, argv, banner, usage);
  ESL_RANDOMNESS *r      = esl_randomness_CreateFast(esl_opt_GetInteger(go, "-s"));
  ESL_GENCODE    *gcode  = NULL;
  ESL_ALPHABET   *abcAA  = NULL;
  ESL_ALPHABET   *abcDNA = NULL;
  P7_BG          *bgAA   = NULL;
  P7_BG          *bgDNA  = NULL;
  P7_CODONTABLE  *ct     = NULL;
  int             M      = esl_opt_GetInteger(go, "-M");
  int             N      = esl_opt_GetInteger(go, "-N");

  if ((abcDNA = esl_alphabet_Create(eslDNA))      == NULL)  esl_fatal("failed to create alphabet");
  if ((bgDNA  = p7_bg_Create(abcDNA))             == NULL)  esl_fatal("failed to create null model");
  if ((abcAA  = esl_alphabet_Create(eslAMINO))    == NULL)  esl_fatal("failed to create alphabet");
  if ((bgAA   = p7_bg_Create(abcAA))              == NULL)  esl_fatal("failed to create null model");
  if ((gcode  = esl_gencode_Create(abcDNA,abcAA)) == NULL)  esl_fatal("failed to create gencode");
  if ((ct     = p7_codontable_Create(gcode))      == NULL)  esl_fatal("failed to create codon table");

  utest_fwdbackfs(r, abcAA, abcDNA, gcode, bgAA, bgDNA, ct, M, N);

  esl_alphabet_Destroy(abcDNA);
  esl_alphabet_Destroy(abcAA);
  p7_bg_Destroy(bgDNA);
  p7_bg_Destroy(bgAA);
  esl_gencode_Destroy(gcode);
  p7_codontable_Destroy(ct);

  esl_getopts_Destroy(go);
  esl_randomness_Destroy(r);
  return eslOK;
}
#endif /*p7FWDBACK_FS_TESTDRIVE*/


/*--------------------- end, test driver ------------------------*/



/*****************************************************************
 * 5. Example
 *****************************************************************/

